// Code generated by generate-bun-routes.ts. DO NOT EDIT.

import { bunResolversAdapter } from './adapter'

export const routes = {
  '/api/health': {
    GET: bunResolversAdapter('health.healthCheck'),
  },
  '/api/auth/login': {
    POST: bunResolversAdapter('auth.login'),
  },
  '/api/auth/refresh': {
    POST: bunResolversAdapter('auth.refresh'),
  },
  '/api/auth/me': {
    GET: bunResolversAdapter('auth.me'),
  },
  '/api/appointments': {
    GET: bunResolversAdapter('appointments.listAppointments'),
    POST: bunResolversAdapter('appointments.createAppointment'),
  },
  '/api/appointments/count': {
    GET: bunResolversAdapter('appointments.countAppointments'),
  },
  '/api/appointments/calendar': {
    GET: bunResolversAdapter('appointments.getAppointmentsCalendar'),
  },
  '/api/appointments/calendar/count': {
    GET: bunResolversAdapter('appointments.getAppointmentsCalendarCount'),
  },
  '/api/appointments/:id': {
    GET: bunResolversAdapter('appointments.getAppointmentById'),
    PUT: bunResolversAdapter('appointments.updateAppointment'),
    DELETE: bunResolversAdapter('appointments.deleteAppointment'),
  },
  '/api/customers': {
    GET: bunResolversAdapter('customers.listCustomers'),
    POST: bunResolversAdapter('customers.createCustomer'),
  },
  '/api/customers/count': {
    GET: bunResolversAdapter('customers.countCustomers'),
  },
  '/api/customers/:id': {
    GET: bunResolversAdapter('customers.getCustomerById'),
    PUT: bunResolversAdapter('customers.updateCustomer'),
    DELETE: bunResolversAdapter('customers.deleteCustomer'),
  },
  '/api/secretaries': {
    GET: bunResolversAdapter('secretaries.listSecretaries'),
    POST: bunResolversAdapter('secretaries.createSecretary'),
  },
  '/api/secretaries/count': {
    GET: bunResolversAdapter('secretaries.countSecretaries'),
  },
  '/api/secretaries/:id': {
    GET: bunResolversAdapter('secretaries.getSecretaryById'),
    PUT: bunResolversAdapter('secretaries.updateSecretary'),
    DELETE: bunResolversAdapter('secretaries.deleteSecretary'),
  },
  '/api/services-available': {
    GET: bunResolversAdapter('servicesAvailable.listServicesAvailable'),
    POST: bunResolversAdapter('servicesAvailable.createServiceAvailable'),
  },
  '/api/services-available/:id': {
    GET: bunResolversAdapter('servicesAvailable.getServiceAvailableById'),
    PUT: bunResolversAdapter('servicesAvailable.updateServiceAvailable'),
    DELETE: bunResolversAdapter('servicesAvailable.deleteServiceAvailable'),
  },
  '/api/services': {
    GET: bunResolversAdapter('services.listServices'),
    POST: bunResolversAdapter('services.createService'),
  },
  '/api/services/count': {
    GET: bunResolversAdapter('services.countServices'),
  },
  '/api/services/:id': {
    GET: bunResolversAdapter('services.getServiceById'),
    PUT: bunResolversAdapter('services.updateService'),
    DELETE: bunResolversAdapter('services.deleteService'),
  },
  '/api/service-groups': {
    GET: bunResolversAdapter('serviceGroups.listServiceGroups'),
  },
  '/api/specialists': {
    GET: bunResolversAdapter('specialists.listSpecialists'),
    POST: bunResolversAdapter('specialists.createSpecialist'),
  },
  '/api/specialists/count': {
    GET: bunResolversAdapter('specialists.countSpecialists'),
  },
  '/api/specialists/:id/services': {
    GET: bunResolversAdapter('specialists.getSpecialistServices'),
  },
  '/api/specialists/:id/specializations': {
    GET: bunResolversAdapter('specialists.getSpecialistSpecializations'),
  },
  '/api/specialists/:id/appointments': {
    GET: bunResolversAdapter('specialists.getSpecialistAppointments'),
  },
  '/api/specialists/:id/services/:service_id': {
    GET: bunResolversAdapter('specialists.getSpecialistService'),
  },
  '/api/specialists/:id': {
    GET: bunResolversAdapter('specialists.getSpecialistById'),
    PUT: bunResolversAdapter('specialists.updateSpecialist'),
    DELETE: bunResolversAdapter('specialists.deleteSpecialist'),
  },
  '/api/specializations': {
    GET: bunResolversAdapter('specializations.listSpecializations'),
    POST: bunResolversAdapter('specializations.createSpecialization'),
  },
  '/api/specializations/:id': {
    PUT: bunResolversAdapter('specializations.updateSpecialization'),
    DELETE: bunResolversAdapter('specializations.deleteSpecialization'),
  },
  '/api/test/init': {
    GET: bunResolversAdapter('test.initTest'),
  },
  '/api/test/stats': {
    GET: bunResolversAdapter('test.statsTest'),
  },
  '/api/test/debug-claims': {
    GET: bunResolversAdapter('test.debugClaimsTest'),
  },
} satisfies Bun.Serve.Options<any, any>['routes']
