
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `secretaries` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model secretaries
 * 
 */
export type secretariesModel = runtime.Types.Result.DefaultSelection<Prisma.$secretariesPayload>

export type AggregateSecretaries = {
  _count: SecretariesCountAggregateOutputType | null
  _min: SecretariesMinAggregateOutputType | null
  _max: SecretariesMaxAggregateOutputType | null
}

export type SecretariesMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  password: string | null
  phone: string | null
  birthdate: Date | null
  cpf: string | null
  cnpj: string | null
}

export type SecretariesMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  password: string | null
  phone: string | null
  birthdate: Date | null
  cpf: string | null
  cnpj: string | null
}

export type SecretariesCountAggregateOutputType = {
  id: number
  name: number
  email: number
  password: number
  phone: number
  birthdate: number
  cpf: number
  cnpj: number
  _all: number
}


export type SecretariesMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  password?: true
  phone?: true
  birthdate?: true
  cpf?: true
  cnpj?: true
}

export type SecretariesMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  password?: true
  phone?: true
  birthdate?: true
  cpf?: true
  cnpj?: true
}

export type SecretariesCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  password?: true
  phone?: true
  birthdate?: true
  cpf?: true
  cnpj?: true
  _all?: true
}

export type SecretariesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which secretaries to aggregate.
   */
  where?: Prisma.secretariesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of secretaries to fetch.
   */
  orderBy?: Prisma.secretariesOrderByWithRelationInput | Prisma.secretariesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.secretariesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` secretaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` secretaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned secretaries
  **/
  _count?: true | SecretariesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SecretariesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SecretariesMaxAggregateInputType
}

export type GetSecretariesAggregateType<T extends SecretariesAggregateArgs> = {
      [P in keyof T & keyof AggregateSecretaries]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSecretaries[P]>
    : Prisma.GetScalarType<T[P], AggregateSecretaries[P]>
}




export type secretariesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.secretariesWhereInput
  orderBy?: Prisma.secretariesOrderByWithAggregationInput | Prisma.secretariesOrderByWithAggregationInput[]
  by: Prisma.SecretariesScalarFieldEnum[] | Prisma.SecretariesScalarFieldEnum
  having?: Prisma.secretariesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SecretariesCountAggregateInputType | true
  _min?: SecretariesMinAggregateInputType
  _max?: SecretariesMaxAggregateInputType
}

export type SecretariesGroupByOutputType = {
  id: string
  name: string
  email: string
  password: string
  phone: string
  birthdate: Date
  cpf: string
  cnpj: string | null
  _count: SecretariesCountAggregateOutputType | null
  _min: SecretariesMinAggregateOutputType | null
  _max: SecretariesMaxAggregateOutputType | null
}

export type GetSecretariesGroupByPayload<T extends secretariesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SecretariesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SecretariesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SecretariesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SecretariesGroupByOutputType[P]>
      }
    >
  >



export type secretariesWhereInput = {
  AND?: Prisma.secretariesWhereInput | Prisma.secretariesWhereInput[]
  OR?: Prisma.secretariesWhereInput[]
  NOT?: Prisma.secretariesWhereInput | Prisma.secretariesWhereInput[]
  id?: Prisma.UuidFilter<"secretaries"> | string
  name?: Prisma.StringFilter<"secretaries"> | string
  email?: Prisma.StringFilter<"secretaries"> | string
  password?: Prisma.StringFilter<"secretaries"> | string
  phone?: Prisma.StringFilter<"secretaries"> | string
  birthdate?: Prisma.DateTimeFilter<"secretaries"> | Date | string
  cpf?: Prisma.StringFilter<"secretaries"> | string
  cnpj?: Prisma.StringNullableFilter<"secretaries"> | string | null
}

export type secretariesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type secretariesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.secretariesWhereInput | Prisma.secretariesWhereInput[]
  OR?: Prisma.secretariesWhereInput[]
  NOT?: Prisma.secretariesWhereInput | Prisma.secretariesWhereInput[]
  name?: Prisma.StringFilter<"secretaries"> | string
  password?: Prisma.StringFilter<"secretaries"> | string
  phone?: Prisma.StringFilter<"secretaries"> | string
  birthdate?: Prisma.DateTimeFilter<"secretaries"> | Date | string
  cpf?: Prisma.StringFilter<"secretaries"> | string
  cnpj?: Prisma.StringNullableFilter<"secretaries"> | string | null
}, "id" | "email">

export type secretariesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.secretariesCountOrderByAggregateInput
  _max?: Prisma.secretariesMaxOrderByAggregateInput
  _min?: Prisma.secretariesMinOrderByAggregateInput
}

export type secretariesScalarWhereWithAggregatesInput = {
  AND?: Prisma.secretariesScalarWhereWithAggregatesInput | Prisma.secretariesScalarWhereWithAggregatesInput[]
  OR?: Prisma.secretariesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.secretariesScalarWhereWithAggregatesInput | Prisma.secretariesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"secretaries"> | string
  name?: Prisma.StringWithAggregatesFilter<"secretaries"> | string
  email?: Prisma.StringWithAggregatesFilter<"secretaries"> | string
  password?: Prisma.StringWithAggregatesFilter<"secretaries"> | string
  phone?: Prisma.StringWithAggregatesFilter<"secretaries"> | string
  birthdate?: Prisma.DateTimeWithAggregatesFilter<"secretaries"> | Date | string
  cpf?: Prisma.StringWithAggregatesFilter<"secretaries"> | string
  cnpj?: Prisma.StringNullableWithAggregatesFilter<"secretaries"> | string | null
}

export type secretariesCreateInput = {
  id?: string
  name: string
  email: string
  password: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
}

export type secretariesUncheckedCreateInput = {
  id?: string
  name: string
  email: string
  password: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
}

export type secretariesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type secretariesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type secretariesCreateManyInput = {
  id?: string
  name: string
  email: string
  password: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
}

export type secretariesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type secretariesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type secretariesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrder
}

export type secretariesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrder
}

export type secretariesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrder
}



export type secretariesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  phone?: boolean
  birthdate?: boolean
  cpf?: boolean
  cnpj?: boolean
}, ExtArgs["result"]["secretaries"]>

export type secretariesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  phone?: boolean
  birthdate?: boolean
  cpf?: boolean
  cnpj?: boolean
}, ExtArgs["result"]["secretaries"]>

export type secretariesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  phone?: boolean
  birthdate?: boolean
  cpf?: boolean
  cnpj?: boolean
}, ExtArgs["result"]["secretaries"]>

export type secretariesSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  password?: boolean
  phone?: boolean
  birthdate?: boolean
  cpf?: boolean
  cnpj?: boolean
}

export type secretariesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "password" | "phone" | "birthdate" | "cpf" | "cnpj", ExtArgs["result"]["secretaries"]>

export type $secretariesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "secretaries"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
    password: string
    phone: string
    birthdate: Date
    cpf: string
    cnpj: string | null
  }, ExtArgs["result"]["secretaries"]>
  composites: {}
}

export type secretariesGetPayload<S extends boolean | null | undefined | secretariesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$secretariesPayload, S>

export type secretariesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<secretariesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SecretariesCountAggregateInputType | true
  }

export interface secretariesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['secretaries'], meta: { name: 'secretaries' } }
  /**
   * Find zero or one Secretaries that matches the filter.
   * @param {secretariesFindUniqueArgs} args - Arguments to find a Secretaries
   * @example
   * // Get one Secretaries
   * const secretaries = await prisma.secretaries.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends secretariesFindUniqueArgs>(args: Prisma.SelectSubset<T, secretariesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__secretariesClient<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Secretaries that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {secretariesFindUniqueOrThrowArgs} args - Arguments to find a Secretaries
   * @example
   * // Get one Secretaries
   * const secretaries = await prisma.secretaries.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends secretariesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, secretariesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__secretariesClient<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Secretaries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {secretariesFindFirstArgs} args - Arguments to find a Secretaries
   * @example
   * // Get one Secretaries
   * const secretaries = await prisma.secretaries.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends secretariesFindFirstArgs>(args?: Prisma.SelectSubset<T, secretariesFindFirstArgs<ExtArgs>>): Prisma.Prisma__secretariesClient<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Secretaries that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {secretariesFindFirstOrThrowArgs} args - Arguments to find a Secretaries
   * @example
   * // Get one Secretaries
   * const secretaries = await prisma.secretaries.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends secretariesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, secretariesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__secretariesClient<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Secretaries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {secretariesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Secretaries
   * const secretaries = await prisma.secretaries.findMany()
   * 
   * // Get first 10 Secretaries
   * const secretaries = await prisma.secretaries.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const secretariesWithIdOnly = await prisma.secretaries.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends secretariesFindManyArgs>(args?: Prisma.SelectSubset<T, secretariesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Secretaries.
   * @param {secretariesCreateArgs} args - Arguments to create a Secretaries.
   * @example
   * // Create one Secretaries
   * const Secretaries = await prisma.secretaries.create({
   *   data: {
   *     // ... data to create a Secretaries
   *   }
   * })
   * 
   */
  create<T extends secretariesCreateArgs>(args: Prisma.SelectSubset<T, secretariesCreateArgs<ExtArgs>>): Prisma.Prisma__secretariesClient<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Secretaries.
   * @param {secretariesCreateManyArgs} args - Arguments to create many Secretaries.
   * @example
   * // Create many Secretaries
   * const secretaries = await prisma.secretaries.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends secretariesCreateManyArgs>(args?: Prisma.SelectSubset<T, secretariesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Secretaries and returns the data saved in the database.
   * @param {secretariesCreateManyAndReturnArgs} args - Arguments to create many Secretaries.
   * @example
   * // Create many Secretaries
   * const secretaries = await prisma.secretaries.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Secretaries and only return the `id`
   * const secretariesWithIdOnly = await prisma.secretaries.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends secretariesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, secretariesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Secretaries.
   * @param {secretariesDeleteArgs} args - Arguments to delete one Secretaries.
   * @example
   * // Delete one Secretaries
   * const Secretaries = await prisma.secretaries.delete({
   *   where: {
   *     // ... filter to delete one Secretaries
   *   }
   * })
   * 
   */
  delete<T extends secretariesDeleteArgs>(args: Prisma.SelectSubset<T, secretariesDeleteArgs<ExtArgs>>): Prisma.Prisma__secretariesClient<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Secretaries.
   * @param {secretariesUpdateArgs} args - Arguments to update one Secretaries.
   * @example
   * // Update one Secretaries
   * const secretaries = await prisma.secretaries.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends secretariesUpdateArgs>(args: Prisma.SelectSubset<T, secretariesUpdateArgs<ExtArgs>>): Prisma.Prisma__secretariesClient<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Secretaries.
   * @param {secretariesDeleteManyArgs} args - Arguments to filter Secretaries to delete.
   * @example
   * // Delete a few Secretaries
   * const { count } = await prisma.secretaries.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends secretariesDeleteManyArgs>(args?: Prisma.SelectSubset<T, secretariesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Secretaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {secretariesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Secretaries
   * const secretaries = await prisma.secretaries.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends secretariesUpdateManyArgs>(args: Prisma.SelectSubset<T, secretariesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Secretaries and returns the data updated in the database.
   * @param {secretariesUpdateManyAndReturnArgs} args - Arguments to update many Secretaries.
   * @example
   * // Update many Secretaries
   * const secretaries = await prisma.secretaries.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Secretaries and only return the `id`
   * const secretariesWithIdOnly = await prisma.secretaries.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends secretariesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, secretariesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Secretaries.
   * @param {secretariesUpsertArgs} args - Arguments to update or create a Secretaries.
   * @example
   * // Update or create a Secretaries
   * const secretaries = await prisma.secretaries.upsert({
   *   create: {
   *     // ... data to create a Secretaries
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Secretaries we want to update
   *   }
   * })
   */
  upsert<T extends secretariesUpsertArgs>(args: Prisma.SelectSubset<T, secretariesUpsertArgs<ExtArgs>>): Prisma.Prisma__secretariesClient<runtime.Types.Result.GetResult<Prisma.$secretariesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Secretaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {secretariesCountArgs} args - Arguments to filter Secretaries to count.
   * @example
   * // Count the number of Secretaries
   * const count = await prisma.secretaries.count({
   *   where: {
   *     // ... the filter for the Secretaries we want to count
   *   }
   * })
  **/
  count<T extends secretariesCountArgs>(
    args?: Prisma.Subset<T, secretariesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SecretariesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Secretaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SecretariesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SecretariesAggregateArgs>(args: Prisma.Subset<T, SecretariesAggregateArgs>): Prisma.PrismaPromise<GetSecretariesAggregateType<T>>

  /**
   * Group by Secretaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {secretariesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends secretariesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: secretariesGroupByArgs['orderBy'] }
      : { orderBy?: secretariesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, secretariesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSecretariesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the secretaries model
 */
readonly fields: secretariesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for secretaries.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__secretariesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the secretaries model
 */
export interface secretariesFieldRefs {
  readonly id: Prisma.FieldRef<"secretaries", 'String'>
  readonly name: Prisma.FieldRef<"secretaries", 'String'>
  readonly email: Prisma.FieldRef<"secretaries", 'String'>
  readonly password: Prisma.FieldRef<"secretaries", 'String'>
  readonly phone: Prisma.FieldRef<"secretaries", 'String'>
  readonly birthdate: Prisma.FieldRef<"secretaries", 'DateTime'>
  readonly cpf: Prisma.FieldRef<"secretaries", 'String'>
  readonly cnpj: Prisma.FieldRef<"secretaries", 'String'>
}
    

// Custom InputTypes
/**
 * secretaries findUnique
 */
export type secretariesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * Filter, which secretaries to fetch.
   */
  where: Prisma.secretariesWhereUniqueInput
}

/**
 * secretaries findUniqueOrThrow
 */
export type secretariesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * Filter, which secretaries to fetch.
   */
  where: Prisma.secretariesWhereUniqueInput
}

/**
 * secretaries findFirst
 */
export type secretariesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * Filter, which secretaries to fetch.
   */
  where?: Prisma.secretariesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of secretaries to fetch.
   */
  orderBy?: Prisma.secretariesOrderByWithRelationInput | Prisma.secretariesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for secretaries.
   */
  cursor?: Prisma.secretariesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` secretaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` secretaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of secretaries.
   */
  distinct?: Prisma.SecretariesScalarFieldEnum | Prisma.SecretariesScalarFieldEnum[]
}

/**
 * secretaries findFirstOrThrow
 */
export type secretariesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * Filter, which secretaries to fetch.
   */
  where?: Prisma.secretariesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of secretaries to fetch.
   */
  orderBy?: Prisma.secretariesOrderByWithRelationInput | Prisma.secretariesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for secretaries.
   */
  cursor?: Prisma.secretariesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` secretaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` secretaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of secretaries.
   */
  distinct?: Prisma.SecretariesScalarFieldEnum | Prisma.SecretariesScalarFieldEnum[]
}

/**
 * secretaries findMany
 */
export type secretariesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * Filter, which secretaries to fetch.
   */
  where?: Prisma.secretariesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of secretaries to fetch.
   */
  orderBy?: Prisma.secretariesOrderByWithRelationInput | Prisma.secretariesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing secretaries.
   */
  cursor?: Prisma.secretariesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` secretaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` secretaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of secretaries.
   */
  distinct?: Prisma.SecretariesScalarFieldEnum | Prisma.SecretariesScalarFieldEnum[]
}

/**
 * secretaries create
 */
export type secretariesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * The data needed to create a secretaries.
   */
  data: Prisma.XOR<Prisma.secretariesCreateInput, Prisma.secretariesUncheckedCreateInput>
}

/**
 * secretaries createMany
 */
export type secretariesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many secretaries.
   */
  data: Prisma.secretariesCreateManyInput | Prisma.secretariesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * secretaries createManyAndReturn
 */
export type secretariesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * The data used to create many secretaries.
   */
  data: Prisma.secretariesCreateManyInput | Prisma.secretariesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * secretaries update
 */
export type secretariesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * The data needed to update a secretaries.
   */
  data: Prisma.XOR<Prisma.secretariesUpdateInput, Prisma.secretariesUncheckedUpdateInput>
  /**
   * Choose, which secretaries to update.
   */
  where: Prisma.secretariesWhereUniqueInput
}

/**
 * secretaries updateMany
 */
export type secretariesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update secretaries.
   */
  data: Prisma.XOR<Prisma.secretariesUpdateManyMutationInput, Prisma.secretariesUncheckedUpdateManyInput>
  /**
   * Filter which secretaries to update
   */
  where?: Prisma.secretariesWhereInput
  /**
   * Limit how many secretaries to update.
   */
  limit?: number
}

/**
 * secretaries updateManyAndReturn
 */
export type secretariesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * The data used to update secretaries.
   */
  data: Prisma.XOR<Prisma.secretariesUpdateManyMutationInput, Prisma.secretariesUncheckedUpdateManyInput>
  /**
   * Filter which secretaries to update
   */
  where?: Prisma.secretariesWhereInput
  /**
   * Limit how many secretaries to update.
   */
  limit?: number
}

/**
 * secretaries upsert
 */
export type secretariesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * The filter to search for the secretaries to update in case it exists.
   */
  where: Prisma.secretariesWhereUniqueInput
  /**
   * In case the secretaries found by the `where` argument doesn't exist, create a new secretaries with this data.
   */
  create: Prisma.XOR<Prisma.secretariesCreateInput, Prisma.secretariesUncheckedCreateInput>
  /**
   * In case the secretaries was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.secretariesUpdateInput, Prisma.secretariesUncheckedUpdateInput>
}

/**
 * secretaries delete
 */
export type secretariesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
  /**
   * Filter which secretaries to delete.
   */
  where: Prisma.secretariesWhereUniqueInput
}

/**
 * secretaries deleteMany
 */
export type secretariesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which secretaries to delete
   */
  where?: Prisma.secretariesWhereInput
  /**
   * Limit how many secretaries to delete.
   */
  limit?: number
}

/**
 * secretaries without action
 */
export type secretariesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the secretaries
   */
  select?: Prisma.secretariesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the secretaries
   */
  omit?: Prisma.secretariesOmit<ExtArgs> | null
}
