
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `services` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model services
 * 
 */
export type servicesModel = runtime.Types.Result.DefaultSelection<Prisma.$servicesPayload>

export type AggregateServices = {
  _count: ServicesCountAggregateOutputType | null
  _avg: ServicesAvgAggregateOutputType | null
  _sum: ServicesSumAggregateOutputType | null
  _min: ServicesMinAggregateOutputType | null
  _max: ServicesMaxAggregateOutputType | null
}

export type ServicesAvgAggregateOutputType = {
  price: number | null
  duration: number | null
}

export type ServicesSumAggregateOutputType = {
  price: number | null
  duration: number | null
}

export type ServicesMinAggregateOutputType = {
  id: string | null
  service_name_id: string | null
  specialist_id: string | null
  price: number | null
  duration: number | null
}

export type ServicesMaxAggregateOutputType = {
  id: string | null
  service_name_id: string | null
  specialist_id: string | null
  price: number | null
  duration: number | null
}

export type ServicesCountAggregateOutputType = {
  id: number
  service_name_id: number
  specialist_id: number
  price: number
  duration: number
  _all: number
}


export type ServicesAvgAggregateInputType = {
  price?: true
  duration?: true
}

export type ServicesSumAggregateInputType = {
  price?: true
  duration?: true
}

export type ServicesMinAggregateInputType = {
  id?: true
  service_name_id?: true
  specialist_id?: true
  price?: true
  duration?: true
}

export type ServicesMaxAggregateInputType = {
  id?: true
  service_name_id?: true
  specialist_id?: true
  price?: true
  duration?: true
}

export type ServicesCountAggregateInputType = {
  id?: true
  service_name_id?: true
  specialist_id?: true
  price?: true
  duration?: true
  _all?: true
}

export type ServicesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which services to aggregate.
   */
  where?: Prisma.servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of services to fetch.
   */
  orderBy?: Prisma.servicesOrderByWithRelationInput | Prisma.servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned services
  **/
  _count?: true | ServicesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ServicesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ServicesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServicesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServicesMaxAggregateInputType
}

export type GetServicesAggregateType<T extends ServicesAggregateArgs> = {
      [P in keyof T & keyof AggregateServices]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServices[P]>
    : Prisma.GetScalarType<T[P], AggregateServices[P]>
}




export type servicesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.servicesWhereInput
  orderBy?: Prisma.servicesOrderByWithAggregationInput | Prisma.servicesOrderByWithAggregationInput[]
  by: Prisma.ServicesScalarFieldEnum[] | Prisma.ServicesScalarFieldEnum
  having?: Prisma.servicesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServicesCountAggregateInputType | true
  _avg?: ServicesAvgAggregateInputType
  _sum?: ServicesSumAggregateInputType
  _min?: ServicesMinAggregateInputType
  _max?: ServicesMaxAggregateInputType
}

export type ServicesGroupByOutputType = {
  id: string
  service_name_id: string
  specialist_id: string
  price: number
  duration: number
  _count: ServicesCountAggregateOutputType | null
  _avg: ServicesAvgAggregateOutputType | null
  _sum: ServicesSumAggregateOutputType | null
  _min: ServicesMinAggregateOutputType | null
  _max: ServicesMaxAggregateOutputType | null
}

export type GetServicesGroupByPayload<T extends servicesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServicesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServicesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServicesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServicesGroupByOutputType[P]>
      }
    >
  >



export type servicesWhereInput = {
  AND?: Prisma.servicesWhereInput | Prisma.servicesWhereInput[]
  OR?: Prisma.servicesWhereInput[]
  NOT?: Prisma.servicesWhereInput | Prisma.servicesWhereInput[]
  id?: Prisma.UuidFilter<"services"> | string
  service_name_id?: Prisma.UuidFilter<"services"> | string
  specialist_id?: Prisma.UuidFilter<"services"> | string
  price?: Prisma.IntFilter<"services"> | number
  duration?: Prisma.IntFilter<"services"> | number
  service_names?: Prisma.XOR<Prisma.Service_namesScalarRelationFilter, Prisma.service_namesWhereInput>
  specialists?: Prisma.XOR<Prisma.SpecialistsScalarRelationFilter, Prisma.specialistsWhereInput>
}

export type servicesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  service_name_id?: Prisma.SortOrder
  specialist_id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  service_names?: Prisma.service_namesOrderByWithRelationInput
  specialists?: Prisma.specialistsOrderByWithRelationInput
}

export type servicesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  service_name_id_specialist_id?: Prisma.servicesService_name_idSpecialist_idCompoundUniqueInput
  AND?: Prisma.servicesWhereInput | Prisma.servicesWhereInput[]
  OR?: Prisma.servicesWhereInput[]
  NOT?: Prisma.servicesWhereInput | Prisma.servicesWhereInput[]
  service_name_id?: Prisma.UuidFilter<"services"> | string
  specialist_id?: Prisma.UuidFilter<"services"> | string
  price?: Prisma.IntFilter<"services"> | number
  duration?: Prisma.IntFilter<"services"> | number
  service_names?: Prisma.XOR<Prisma.Service_namesScalarRelationFilter, Prisma.service_namesWhereInput>
  specialists?: Prisma.XOR<Prisma.SpecialistsScalarRelationFilter, Prisma.specialistsWhereInput>
}, "id" | "service_name_id_specialist_id">

export type servicesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  service_name_id?: Prisma.SortOrder
  specialist_id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  _count?: Prisma.servicesCountOrderByAggregateInput
  _avg?: Prisma.servicesAvgOrderByAggregateInput
  _max?: Prisma.servicesMaxOrderByAggregateInput
  _min?: Prisma.servicesMinOrderByAggregateInput
  _sum?: Prisma.servicesSumOrderByAggregateInput
}

export type servicesScalarWhereWithAggregatesInput = {
  AND?: Prisma.servicesScalarWhereWithAggregatesInput | Prisma.servicesScalarWhereWithAggregatesInput[]
  OR?: Prisma.servicesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.servicesScalarWhereWithAggregatesInput | Prisma.servicesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"services"> | string
  service_name_id?: Prisma.UuidWithAggregatesFilter<"services"> | string
  specialist_id?: Prisma.UuidWithAggregatesFilter<"services"> | string
  price?: Prisma.IntWithAggregatesFilter<"services"> | number
  duration?: Prisma.IntWithAggregatesFilter<"services"> | number
}

export type servicesCreateInput = {
  id?: string
  price: number
  duration: number
  service_names: Prisma.service_namesCreateNestedOneWithoutServicesInput
  specialists: Prisma.specialistsCreateNestedOneWithoutServicesInput
}

export type servicesUncheckedCreateInput = {
  id?: string
  service_name_id: string
  specialist_id: string
  price: number
  duration: number
}

export type servicesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  service_names?: Prisma.service_namesUpdateOneRequiredWithoutServicesNestedInput
  specialists?: Prisma.specialistsUpdateOneRequiredWithoutServicesNestedInput
}

export type servicesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  service_name_id?: Prisma.StringFieldUpdateOperationsInput | string
  specialist_id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type servicesCreateManyInput = {
  id?: string
  service_name_id: string
  specialist_id: string
  price: number
  duration: number
}

export type servicesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type servicesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  service_name_id?: Prisma.StringFieldUpdateOperationsInput | string
  specialist_id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ServicesListRelationFilter = {
  every?: Prisma.servicesWhereInput
  some?: Prisma.servicesWhereInput
  none?: Prisma.servicesWhereInput
}

export type servicesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type servicesService_name_idSpecialist_idCompoundUniqueInput = {
  service_name_id: string
  specialist_id: string
}

export type servicesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  service_name_id?: Prisma.SortOrder
  specialist_id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type servicesAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type servicesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  service_name_id?: Prisma.SortOrder
  specialist_id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type servicesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  service_name_id?: Prisma.SortOrder
  specialist_id?: Prisma.SortOrder
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type servicesSumOrderByAggregateInput = {
  price?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type servicesCreateNestedManyWithoutService_namesInput = {
  create?: Prisma.XOR<Prisma.servicesCreateWithoutService_namesInput, Prisma.servicesUncheckedCreateWithoutService_namesInput> | Prisma.servicesCreateWithoutService_namesInput[] | Prisma.servicesUncheckedCreateWithoutService_namesInput[]
  connectOrCreate?: Prisma.servicesCreateOrConnectWithoutService_namesInput | Prisma.servicesCreateOrConnectWithoutService_namesInput[]
  createMany?: Prisma.servicesCreateManyService_namesInputEnvelope
  connect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
}

export type servicesUncheckedCreateNestedManyWithoutService_namesInput = {
  create?: Prisma.XOR<Prisma.servicesCreateWithoutService_namesInput, Prisma.servicesUncheckedCreateWithoutService_namesInput> | Prisma.servicesCreateWithoutService_namesInput[] | Prisma.servicesUncheckedCreateWithoutService_namesInput[]
  connectOrCreate?: Prisma.servicesCreateOrConnectWithoutService_namesInput | Prisma.servicesCreateOrConnectWithoutService_namesInput[]
  createMany?: Prisma.servicesCreateManyService_namesInputEnvelope
  connect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
}

export type servicesUpdateManyWithoutService_namesNestedInput = {
  create?: Prisma.XOR<Prisma.servicesCreateWithoutService_namesInput, Prisma.servicesUncheckedCreateWithoutService_namesInput> | Prisma.servicesCreateWithoutService_namesInput[] | Prisma.servicesUncheckedCreateWithoutService_namesInput[]
  connectOrCreate?: Prisma.servicesCreateOrConnectWithoutService_namesInput | Prisma.servicesCreateOrConnectWithoutService_namesInput[]
  upsert?: Prisma.servicesUpsertWithWhereUniqueWithoutService_namesInput | Prisma.servicesUpsertWithWhereUniqueWithoutService_namesInput[]
  createMany?: Prisma.servicesCreateManyService_namesInputEnvelope
  set?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  disconnect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  delete?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  connect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  update?: Prisma.servicesUpdateWithWhereUniqueWithoutService_namesInput | Prisma.servicesUpdateWithWhereUniqueWithoutService_namesInput[]
  updateMany?: Prisma.servicesUpdateManyWithWhereWithoutService_namesInput | Prisma.servicesUpdateManyWithWhereWithoutService_namesInput[]
  deleteMany?: Prisma.servicesScalarWhereInput | Prisma.servicesScalarWhereInput[]
}

export type servicesUncheckedUpdateManyWithoutService_namesNestedInput = {
  create?: Prisma.XOR<Prisma.servicesCreateWithoutService_namesInput, Prisma.servicesUncheckedCreateWithoutService_namesInput> | Prisma.servicesCreateWithoutService_namesInput[] | Prisma.servicesUncheckedCreateWithoutService_namesInput[]
  connectOrCreate?: Prisma.servicesCreateOrConnectWithoutService_namesInput | Prisma.servicesCreateOrConnectWithoutService_namesInput[]
  upsert?: Prisma.servicesUpsertWithWhereUniqueWithoutService_namesInput | Prisma.servicesUpsertWithWhereUniqueWithoutService_namesInput[]
  createMany?: Prisma.servicesCreateManyService_namesInputEnvelope
  set?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  disconnect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  delete?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  connect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  update?: Prisma.servicesUpdateWithWhereUniqueWithoutService_namesInput | Prisma.servicesUpdateWithWhereUniqueWithoutService_namesInput[]
  updateMany?: Prisma.servicesUpdateManyWithWhereWithoutService_namesInput | Prisma.servicesUpdateManyWithWhereWithoutService_namesInput[]
  deleteMany?: Prisma.servicesScalarWhereInput | Prisma.servicesScalarWhereInput[]
}

export type servicesCreateNestedManyWithoutSpecialistsInput = {
  create?: Prisma.XOR<Prisma.servicesCreateWithoutSpecialistsInput, Prisma.servicesUncheckedCreateWithoutSpecialistsInput> | Prisma.servicesCreateWithoutSpecialistsInput[] | Prisma.servicesUncheckedCreateWithoutSpecialistsInput[]
  connectOrCreate?: Prisma.servicesCreateOrConnectWithoutSpecialistsInput | Prisma.servicesCreateOrConnectWithoutSpecialistsInput[]
  createMany?: Prisma.servicesCreateManySpecialistsInputEnvelope
  connect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
}

export type servicesUncheckedCreateNestedManyWithoutSpecialistsInput = {
  create?: Prisma.XOR<Prisma.servicesCreateWithoutSpecialistsInput, Prisma.servicesUncheckedCreateWithoutSpecialistsInput> | Prisma.servicesCreateWithoutSpecialistsInput[] | Prisma.servicesUncheckedCreateWithoutSpecialistsInput[]
  connectOrCreate?: Prisma.servicesCreateOrConnectWithoutSpecialistsInput | Prisma.servicesCreateOrConnectWithoutSpecialistsInput[]
  createMany?: Prisma.servicesCreateManySpecialistsInputEnvelope
  connect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
}

export type servicesUpdateManyWithoutSpecialistsNestedInput = {
  create?: Prisma.XOR<Prisma.servicesCreateWithoutSpecialistsInput, Prisma.servicesUncheckedCreateWithoutSpecialistsInput> | Prisma.servicesCreateWithoutSpecialistsInput[] | Prisma.servicesUncheckedCreateWithoutSpecialistsInput[]
  connectOrCreate?: Prisma.servicesCreateOrConnectWithoutSpecialistsInput | Prisma.servicesCreateOrConnectWithoutSpecialistsInput[]
  upsert?: Prisma.servicesUpsertWithWhereUniqueWithoutSpecialistsInput | Prisma.servicesUpsertWithWhereUniqueWithoutSpecialistsInput[]
  createMany?: Prisma.servicesCreateManySpecialistsInputEnvelope
  set?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  disconnect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  delete?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  connect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  update?: Prisma.servicesUpdateWithWhereUniqueWithoutSpecialistsInput | Prisma.servicesUpdateWithWhereUniqueWithoutSpecialistsInput[]
  updateMany?: Prisma.servicesUpdateManyWithWhereWithoutSpecialistsInput | Prisma.servicesUpdateManyWithWhereWithoutSpecialistsInput[]
  deleteMany?: Prisma.servicesScalarWhereInput | Prisma.servicesScalarWhereInput[]
}

export type servicesUncheckedUpdateManyWithoutSpecialistsNestedInput = {
  create?: Prisma.XOR<Prisma.servicesCreateWithoutSpecialistsInput, Prisma.servicesUncheckedCreateWithoutSpecialistsInput> | Prisma.servicesCreateWithoutSpecialistsInput[] | Prisma.servicesUncheckedCreateWithoutSpecialistsInput[]
  connectOrCreate?: Prisma.servicesCreateOrConnectWithoutSpecialistsInput | Prisma.servicesCreateOrConnectWithoutSpecialistsInput[]
  upsert?: Prisma.servicesUpsertWithWhereUniqueWithoutSpecialistsInput | Prisma.servicesUpsertWithWhereUniqueWithoutSpecialistsInput[]
  createMany?: Prisma.servicesCreateManySpecialistsInputEnvelope
  set?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  disconnect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  delete?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  connect?: Prisma.servicesWhereUniqueInput | Prisma.servicesWhereUniqueInput[]
  update?: Prisma.servicesUpdateWithWhereUniqueWithoutSpecialistsInput | Prisma.servicesUpdateWithWhereUniqueWithoutSpecialistsInput[]
  updateMany?: Prisma.servicesUpdateManyWithWhereWithoutSpecialistsInput | Prisma.servicesUpdateManyWithWhereWithoutSpecialistsInput[]
  deleteMany?: Prisma.servicesScalarWhereInput | Prisma.servicesScalarWhereInput[]
}

export type servicesCreateWithoutService_namesInput = {
  id?: string
  price: number
  duration: number
  specialists: Prisma.specialistsCreateNestedOneWithoutServicesInput
}

export type servicesUncheckedCreateWithoutService_namesInput = {
  id?: string
  specialist_id: string
  price: number
  duration: number
}

export type servicesCreateOrConnectWithoutService_namesInput = {
  where: Prisma.servicesWhereUniqueInput
  create: Prisma.XOR<Prisma.servicesCreateWithoutService_namesInput, Prisma.servicesUncheckedCreateWithoutService_namesInput>
}

export type servicesCreateManyService_namesInputEnvelope = {
  data: Prisma.servicesCreateManyService_namesInput | Prisma.servicesCreateManyService_namesInput[]
  skipDuplicates?: boolean
}

export type servicesUpsertWithWhereUniqueWithoutService_namesInput = {
  where: Prisma.servicesWhereUniqueInput
  update: Prisma.XOR<Prisma.servicesUpdateWithoutService_namesInput, Prisma.servicesUncheckedUpdateWithoutService_namesInput>
  create: Prisma.XOR<Prisma.servicesCreateWithoutService_namesInput, Prisma.servicesUncheckedCreateWithoutService_namesInput>
}

export type servicesUpdateWithWhereUniqueWithoutService_namesInput = {
  where: Prisma.servicesWhereUniqueInput
  data: Prisma.XOR<Prisma.servicesUpdateWithoutService_namesInput, Prisma.servicesUncheckedUpdateWithoutService_namesInput>
}

export type servicesUpdateManyWithWhereWithoutService_namesInput = {
  where: Prisma.servicesScalarWhereInput
  data: Prisma.XOR<Prisma.servicesUpdateManyMutationInput, Prisma.servicesUncheckedUpdateManyWithoutService_namesInput>
}

export type servicesScalarWhereInput = {
  AND?: Prisma.servicesScalarWhereInput | Prisma.servicesScalarWhereInput[]
  OR?: Prisma.servicesScalarWhereInput[]
  NOT?: Prisma.servicesScalarWhereInput | Prisma.servicesScalarWhereInput[]
  id?: Prisma.UuidFilter<"services"> | string
  service_name_id?: Prisma.UuidFilter<"services"> | string
  specialist_id?: Prisma.UuidFilter<"services"> | string
  price?: Prisma.IntFilter<"services"> | number
  duration?: Prisma.IntFilter<"services"> | number
}

export type servicesCreateWithoutSpecialistsInput = {
  id?: string
  price: number
  duration: number
  service_names: Prisma.service_namesCreateNestedOneWithoutServicesInput
}

export type servicesUncheckedCreateWithoutSpecialistsInput = {
  id?: string
  service_name_id: string
  price: number
  duration: number
}

export type servicesCreateOrConnectWithoutSpecialistsInput = {
  where: Prisma.servicesWhereUniqueInput
  create: Prisma.XOR<Prisma.servicesCreateWithoutSpecialistsInput, Prisma.servicesUncheckedCreateWithoutSpecialistsInput>
}

export type servicesCreateManySpecialistsInputEnvelope = {
  data: Prisma.servicesCreateManySpecialistsInput | Prisma.servicesCreateManySpecialistsInput[]
  skipDuplicates?: boolean
}

export type servicesUpsertWithWhereUniqueWithoutSpecialistsInput = {
  where: Prisma.servicesWhereUniqueInput
  update: Prisma.XOR<Prisma.servicesUpdateWithoutSpecialistsInput, Prisma.servicesUncheckedUpdateWithoutSpecialistsInput>
  create: Prisma.XOR<Prisma.servicesCreateWithoutSpecialistsInput, Prisma.servicesUncheckedCreateWithoutSpecialistsInput>
}

export type servicesUpdateWithWhereUniqueWithoutSpecialistsInput = {
  where: Prisma.servicesWhereUniqueInput
  data: Prisma.XOR<Prisma.servicesUpdateWithoutSpecialistsInput, Prisma.servicesUncheckedUpdateWithoutSpecialistsInput>
}

export type servicesUpdateManyWithWhereWithoutSpecialistsInput = {
  where: Prisma.servicesScalarWhereInput
  data: Prisma.XOR<Prisma.servicesUpdateManyMutationInput, Prisma.servicesUncheckedUpdateManyWithoutSpecialistsInput>
}

export type servicesCreateManyService_namesInput = {
  id?: string
  specialist_id: string
  price: number
  duration: number
}

export type servicesUpdateWithoutService_namesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  specialists?: Prisma.specialistsUpdateOneRequiredWithoutServicesNestedInput
}

export type servicesUncheckedUpdateWithoutService_namesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  specialist_id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type servicesUncheckedUpdateManyWithoutService_namesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  specialist_id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type servicesCreateManySpecialistsInput = {
  id?: string
  service_name_id: string
  price: number
  duration: number
}

export type servicesUpdateWithoutSpecialistsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
  service_names?: Prisma.service_namesUpdateOneRequiredWithoutServicesNestedInput
}

export type servicesUncheckedUpdateWithoutSpecialistsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  service_name_id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}

export type servicesUncheckedUpdateManyWithoutSpecialistsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  service_name_id?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  duration?: Prisma.IntFieldUpdateOperationsInput | number
}



export type servicesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  service_name_id?: boolean
  specialist_id?: boolean
  price?: boolean
  duration?: boolean
  service_names?: boolean | Prisma.service_namesDefaultArgs<ExtArgs>
  specialists?: boolean | Prisma.specialistsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["services"]>

export type servicesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  service_name_id?: boolean
  specialist_id?: boolean
  price?: boolean
  duration?: boolean
  service_names?: boolean | Prisma.service_namesDefaultArgs<ExtArgs>
  specialists?: boolean | Prisma.specialistsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["services"]>

export type servicesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  service_name_id?: boolean
  specialist_id?: boolean
  price?: boolean
  duration?: boolean
  service_names?: boolean | Prisma.service_namesDefaultArgs<ExtArgs>
  specialists?: boolean | Prisma.specialistsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["services"]>

export type servicesSelectScalar = {
  id?: boolean
  service_name_id?: boolean
  specialist_id?: boolean
  price?: boolean
  duration?: boolean
}

export type servicesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "service_name_id" | "specialist_id" | "price" | "duration", ExtArgs["result"]["services"]>
export type servicesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  service_names?: boolean | Prisma.service_namesDefaultArgs<ExtArgs>
  specialists?: boolean | Prisma.specialistsDefaultArgs<ExtArgs>
}
export type servicesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  service_names?: boolean | Prisma.service_namesDefaultArgs<ExtArgs>
  specialists?: boolean | Prisma.specialistsDefaultArgs<ExtArgs>
}
export type servicesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  service_names?: boolean | Prisma.service_namesDefaultArgs<ExtArgs>
  specialists?: boolean | Prisma.specialistsDefaultArgs<ExtArgs>
}

export type $servicesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "services"
  objects: {
    service_names: Prisma.$service_namesPayload<ExtArgs>
    specialists: Prisma.$specialistsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    service_name_id: string
    specialist_id: string
    price: number
    duration: number
  }, ExtArgs["result"]["services"]>
  composites: {}
}

export type servicesGetPayload<S extends boolean | null | undefined | servicesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$servicesPayload, S>

export type servicesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<servicesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServicesCountAggregateInputType | true
  }

export interface servicesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['services'], meta: { name: 'services' } }
  /**
   * Find zero or one Services that matches the filter.
   * @param {servicesFindUniqueArgs} args - Arguments to find a Services
   * @example
   * // Get one Services
   * const services = await prisma.services.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends servicesFindUniqueArgs>(args: Prisma.SelectSubset<T, servicesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__servicesClient<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Services that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {servicesFindUniqueOrThrowArgs} args - Arguments to find a Services
   * @example
   * // Get one Services
   * const services = await prisma.services.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends servicesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, servicesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__servicesClient<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Services that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {servicesFindFirstArgs} args - Arguments to find a Services
   * @example
   * // Get one Services
   * const services = await prisma.services.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends servicesFindFirstArgs>(args?: Prisma.SelectSubset<T, servicesFindFirstArgs<ExtArgs>>): Prisma.Prisma__servicesClient<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Services that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {servicesFindFirstOrThrowArgs} args - Arguments to find a Services
   * @example
   * // Get one Services
   * const services = await prisma.services.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends servicesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, servicesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__servicesClient<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Services that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {servicesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Services
   * const services = await prisma.services.findMany()
   * 
   * // Get first 10 Services
   * const services = await prisma.services.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const servicesWithIdOnly = await prisma.services.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends servicesFindManyArgs>(args?: Prisma.SelectSubset<T, servicesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Services.
   * @param {servicesCreateArgs} args - Arguments to create a Services.
   * @example
   * // Create one Services
   * const Services = await prisma.services.create({
   *   data: {
   *     // ... data to create a Services
   *   }
   * })
   * 
   */
  create<T extends servicesCreateArgs>(args: Prisma.SelectSubset<T, servicesCreateArgs<ExtArgs>>): Prisma.Prisma__servicesClient<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Services.
   * @param {servicesCreateManyArgs} args - Arguments to create many Services.
   * @example
   * // Create many Services
   * const services = await prisma.services.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends servicesCreateManyArgs>(args?: Prisma.SelectSubset<T, servicesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Services and returns the data saved in the database.
   * @param {servicesCreateManyAndReturnArgs} args - Arguments to create many Services.
   * @example
   * // Create many Services
   * const services = await prisma.services.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Services and only return the `id`
   * const servicesWithIdOnly = await prisma.services.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends servicesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, servicesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Services.
   * @param {servicesDeleteArgs} args - Arguments to delete one Services.
   * @example
   * // Delete one Services
   * const Services = await prisma.services.delete({
   *   where: {
   *     // ... filter to delete one Services
   *   }
   * })
   * 
   */
  delete<T extends servicesDeleteArgs>(args: Prisma.SelectSubset<T, servicesDeleteArgs<ExtArgs>>): Prisma.Prisma__servicesClient<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Services.
   * @param {servicesUpdateArgs} args - Arguments to update one Services.
   * @example
   * // Update one Services
   * const services = await prisma.services.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends servicesUpdateArgs>(args: Prisma.SelectSubset<T, servicesUpdateArgs<ExtArgs>>): Prisma.Prisma__servicesClient<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Services.
   * @param {servicesDeleteManyArgs} args - Arguments to filter Services to delete.
   * @example
   * // Delete a few Services
   * const { count } = await prisma.services.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends servicesDeleteManyArgs>(args?: Prisma.SelectSubset<T, servicesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {servicesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Services
   * const services = await prisma.services.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends servicesUpdateManyArgs>(args: Prisma.SelectSubset<T, servicesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Services and returns the data updated in the database.
   * @param {servicesUpdateManyAndReturnArgs} args - Arguments to update many Services.
   * @example
   * // Update many Services
   * const services = await prisma.services.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Services and only return the `id`
   * const servicesWithIdOnly = await prisma.services.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends servicesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, servicesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Services.
   * @param {servicesUpsertArgs} args - Arguments to update or create a Services.
   * @example
   * // Update or create a Services
   * const services = await prisma.services.upsert({
   *   create: {
   *     // ... data to create a Services
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Services we want to update
   *   }
   * })
   */
  upsert<T extends servicesUpsertArgs>(args: Prisma.SelectSubset<T, servicesUpsertArgs<ExtArgs>>): Prisma.Prisma__servicesClient<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {servicesCountArgs} args - Arguments to filter Services to count.
   * @example
   * // Count the number of Services
   * const count = await prisma.services.count({
   *   where: {
   *     // ... the filter for the Services we want to count
   *   }
   * })
  **/
  count<T extends servicesCountArgs>(
    args?: Prisma.Subset<T, servicesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServicesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServicesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServicesAggregateArgs>(args: Prisma.Subset<T, ServicesAggregateArgs>): Prisma.PrismaPromise<GetServicesAggregateType<T>>

  /**
   * Group by Services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {servicesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends servicesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: servicesGroupByArgs['orderBy'] }
      : { orderBy?: servicesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, servicesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServicesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the services model
 */
readonly fields: servicesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for services.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__servicesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  service_names<T extends Prisma.service_namesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.service_namesDefaultArgs<ExtArgs>>): Prisma.Prisma__service_namesClient<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  specialists<T extends Prisma.specialistsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.specialistsDefaultArgs<ExtArgs>>): Prisma.Prisma__specialistsClient<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the services model
 */
export interface servicesFieldRefs {
  readonly id: Prisma.FieldRef<"services", 'String'>
  readonly service_name_id: Prisma.FieldRef<"services", 'String'>
  readonly specialist_id: Prisma.FieldRef<"services", 'String'>
  readonly price: Prisma.FieldRef<"services", 'Int'>
  readonly duration: Prisma.FieldRef<"services", 'Int'>
}
    

// Custom InputTypes
/**
 * services findUnique
 */
export type servicesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  /**
   * Filter, which services to fetch.
   */
  where: Prisma.servicesWhereUniqueInput
}

/**
 * services findUniqueOrThrow
 */
export type servicesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  /**
   * Filter, which services to fetch.
   */
  where: Prisma.servicesWhereUniqueInput
}

/**
 * services findFirst
 */
export type servicesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  /**
   * Filter, which services to fetch.
   */
  where?: Prisma.servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of services to fetch.
   */
  orderBy?: Prisma.servicesOrderByWithRelationInput | Prisma.servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for services.
   */
  cursor?: Prisma.servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of services.
   */
  distinct?: Prisma.ServicesScalarFieldEnum | Prisma.ServicesScalarFieldEnum[]
}

/**
 * services findFirstOrThrow
 */
export type servicesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  /**
   * Filter, which services to fetch.
   */
  where?: Prisma.servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of services to fetch.
   */
  orderBy?: Prisma.servicesOrderByWithRelationInput | Prisma.servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for services.
   */
  cursor?: Prisma.servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of services.
   */
  distinct?: Prisma.ServicesScalarFieldEnum | Prisma.ServicesScalarFieldEnum[]
}

/**
 * services findMany
 */
export type servicesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  /**
   * Filter, which services to fetch.
   */
  where?: Prisma.servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of services to fetch.
   */
  orderBy?: Prisma.servicesOrderByWithRelationInput | Prisma.servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing services.
   */
  cursor?: Prisma.servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of services.
   */
  distinct?: Prisma.ServicesScalarFieldEnum | Prisma.ServicesScalarFieldEnum[]
}

/**
 * services create
 */
export type servicesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  /**
   * The data needed to create a services.
   */
  data: Prisma.XOR<Prisma.servicesCreateInput, Prisma.servicesUncheckedCreateInput>
}

/**
 * services createMany
 */
export type servicesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many services.
   */
  data: Prisma.servicesCreateManyInput | Prisma.servicesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * services createManyAndReturn
 */
export type servicesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * The data used to create many services.
   */
  data: Prisma.servicesCreateManyInput | Prisma.servicesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * services update
 */
export type servicesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  /**
   * The data needed to update a services.
   */
  data: Prisma.XOR<Prisma.servicesUpdateInput, Prisma.servicesUncheckedUpdateInput>
  /**
   * Choose, which services to update.
   */
  where: Prisma.servicesWhereUniqueInput
}

/**
 * services updateMany
 */
export type servicesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update services.
   */
  data: Prisma.XOR<Prisma.servicesUpdateManyMutationInput, Prisma.servicesUncheckedUpdateManyInput>
  /**
   * Filter which services to update
   */
  where?: Prisma.servicesWhereInput
  /**
   * Limit how many services to update.
   */
  limit?: number
}

/**
 * services updateManyAndReturn
 */
export type servicesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * The data used to update services.
   */
  data: Prisma.XOR<Prisma.servicesUpdateManyMutationInput, Prisma.servicesUncheckedUpdateManyInput>
  /**
   * Filter which services to update
   */
  where?: Prisma.servicesWhereInput
  /**
   * Limit how many services to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * services upsert
 */
export type servicesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  /**
   * The filter to search for the services to update in case it exists.
   */
  where: Prisma.servicesWhereUniqueInput
  /**
   * In case the services found by the `where` argument doesn't exist, create a new services with this data.
   */
  create: Prisma.XOR<Prisma.servicesCreateInput, Prisma.servicesUncheckedCreateInput>
  /**
   * In case the services was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.servicesUpdateInput, Prisma.servicesUncheckedUpdateInput>
}

/**
 * services delete
 */
export type servicesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  /**
   * Filter which services to delete.
   */
  where: Prisma.servicesWhereUniqueInput
}

/**
 * services deleteMany
 */
export type servicesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which services to delete
   */
  where?: Prisma.servicesWhereInput
  /**
   * Limit how many services to delete.
   */
  limit?: number
}

/**
 * services without action
 */
export type servicesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
}
