
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `service_names` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model service_names
 * 
 */
export type service_namesModel = runtime.Types.Result.DefaultSelection<Prisma.$service_namesPayload>

export type AggregateService_names = {
  _count: Service_namesCountAggregateOutputType | null
  _min: Service_namesMinAggregateOutputType | null
  _max: Service_namesMaxAggregateOutputType | null
}

export type Service_namesMinAggregateOutputType = {
  id: string | null
  name: string | null
  specialization_id: string | null
}

export type Service_namesMaxAggregateOutputType = {
  id: string | null
  name: string | null
  specialization_id: string | null
}

export type Service_namesCountAggregateOutputType = {
  id: number
  name: number
  specialization_id: number
  _all: number
}


export type Service_namesMinAggregateInputType = {
  id?: true
  name?: true
  specialization_id?: true
}

export type Service_namesMaxAggregateInputType = {
  id?: true
  name?: true
  specialization_id?: true
}

export type Service_namesCountAggregateInputType = {
  id?: true
  name?: true
  specialization_id?: true
  _all?: true
}

export type Service_namesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which service_names to aggregate.
   */
  where?: Prisma.service_namesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of service_names to fetch.
   */
  orderBy?: Prisma.service_namesOrderByWithRelationInput | Prisma.service_namesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.service_namesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` service_names from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` service_names.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned service_names
  **/
  _count?: true | Service_namesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Service_namesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Service_namesMaxAggregateInputType
}

export type GetService_namesAggregateType<T extends Service_namesAggregateArgs> = {
      [P in keyof T & keyof AggregateService_names]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateService_names[P]>
    : Prisma.GetScalarType<T[P], AggregateService_names[P]>
}




export type service_namesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.service_namesWhereInput
  orderBy?: Prisma.service_namesOrderByWithAggregationInput | Prisma.service_namesOrderByWithAggregationInput[]
  by: Prisma.Service_namesScalarFieldEnum[] | Prisma.Service_namesScalarFieldEnum
  having?: Prisma.service_namesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Service_namesCountAggregateInputType | true
  _min?: Service_namesMinAggregateInputType
  _max?: Service_namesMaxAggregateInputType
}

export type Service_namesGroupByOutputType = {
  id: string
  name: string
  specialization_id: string
  _count: Service_namesCountAggregateOutputType | null
  _min: Service_namesMinAggregateOutputType | null
  _max: Service_namesMaxAggregateOutputType | null
}

export type GetService_namesGroupByPayload<T extends service_namesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Service_namesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Service_namesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Service_namesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Service_namesGroupByOutputType[P]>
      }
    >
  >



export type service_namesWhereInput = {
  AND?: Prisma.service_namesWhereInput | Prisma.service_namesWhereInput[]
  OR?: Prisma.service_namesWhereInput[]
  NOT?: Prisma.service_namesWhereInput | Prisma.service_namesWhereInput[]
  id?: Prisma.UuidFilter<"service_names"> | string
  name?: Prisma.StringFilter<"service_names"> | string
  specialization_id?: Prisma.UuidFilter<"service_names"> | string
  appointments?: Prisma.AppointmentsListRelationFilter
  specializations?: Prisma.XOR<Prisma.SpecializationsScalarRelationFilter, Prisma.specializationsWhereInput>
  services?: Prisma.ServicesListRelationFilter
}

export type service_namesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  specialization_id?: Prisma.SortOrder
  appointments?: Prisma.appointmentsOrderByRelationAggregateInput
  specializations?: Prisma.specializationsOrderByWithRelationInput
  services?: Prisma.servicesOrderByRelationAggregateInput
}

export type service_namesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  AND?: Prisma.service_namesWhereInput | Prisma.service_namesWhereInput[]
  OR?: Prisma.service_namesWhereInput[]
  NOT?: Prisma.service_namesWhereInput | Prisma.service_namesWhereInput[]
  specialization_id?: Prisma.UuidFilter<"service_names"> | string
  appointments?: Prisma.AppointmentsListRelationFilter
  specializations?: Prisma.XOR<Prisma.SpecializationsScalarRelationFilter, Prisma.specializationsWhereInput>
  services?: Prisma.ServicesListRelationFilter
}, "id" | "name">

export type service_namesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  specialization_id?: Prisma.SortOrder
  _count?: Prisma.service_namesCountOrderByAggregateInput
  _max?: Prisma.service_namesMaxOrderByAggregateInput
  _min?: Prisma.service_namesMinOrderByAggregateInput
}

export type service_namesScalarWhereWithAggregatesInput = {
  AND?: Prisma.service_namesScalarWhereWithAggregatesInput | Prisma.service_namesScalarWhereWithAggregatesInput[]
  OR?: Prisma.service_namesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.service_namesScalarWhereWithAggregatesInput | Prisma.service_namesScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"service_names"> | string
  name?: Prisma.StringWithAggregatesFilter<"service_names"> | string
  specialization_id?: Prisma.UuidWithAggregatesFilter<"service_names"> | string
}

export type service_namesCreateInput = {
  id?: string
  name: string
  appointments?: Prisma.appointmentsCreateNestedManyWithoutService_namesInput
  specializations: Prisma.specializationsCreateNestedOneWithoutService_namesInput
  services?: Prisma.servicesCreateNestedManyWithoutService_namesInput
}

export type service_namesUncheckedCreateInput = {
  id?: string
  name: string
  specialization_id: string
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutService_namesInput
  services?: Prisma.servicesUncheckedCreateNestedManyWithoutService_namesInput
}

export type service_namesUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  appointments?: Prisma.appointmentsUpdateManyWithoutService_namesNestedInput
  specializations?: Prisma.specializationsUpdateOneRequiredWithoutService_namesNestedInput
  services?: Prisma.servicesUpdateManyWithoutService_namesNestedInput
}

export type service_namesUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialization_id?: Prisma.StringFieldUpdateOperationsInput | string
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutService_namesNestedInput
  services?: Prisma.servicesUncheckedUpdateManyWithoutService_namesNestedInput
}

export type service_namesCreateManyInput = {
  id?: string
  name: string
  specialization_id: string
}

export type service_namesUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type service_namesUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialization_id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Service_namesScalarRelationFilter = {
  is?: Prisma.service_namesWhereInput
  isNot?: Prisma.service_namesWhereInput
}

export type service_namesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  specialization_id?: Prisma.SortOrder
}

export type service_namesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  specialization_id?: Prisma.SortOrder
}

export type service_namesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  specialization_id?: Prisma.SortOrder
}

export type Service_namesListRelationFilter = {
  every?: Prisma.service_namesWhereInput
  some?: Prisma.service_namesWhereInput
  none?: Prisma.service_namesWhereInput
}

export type service_namesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type service_namesCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.service_namesCreateWithoutAppointmentsInput, Prisma.service_namesUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.service_namesCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.service_namesWhereUniqueInput
}

export type service_namesUpdateOneRequiredWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.service_namesCreateWithoutAppointmentsInput, Prisma.service_namesUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.service_namesCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.service_namesUpsertWithoutAppointmentsInput
  connect?: Prisma.service_namesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.service_namesUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.service_namesUpdateWithoutAppointmentsInput>, Prisma.service_namesUncheckedUpdateWithoutAppointmentsInput>
}

export type service_namesCreateNestedOneWithoutServicesInput = {
  create?: Prisma.XOR<Prisma.service_namesCreateWithoutServicesInput, Prisma.service_namesUncheckedCreateWithoutServicesInput>
  connectOrCreate?: Prisma.service_namesCreateOrConnectWithoutServicesInput
  connect?: Prisma.service_namesWhereUniqueInput
}

export type service_namesUpdateOneRequiredWithoutServicesNestedInput = {
  create?: Prisma.XOR<Prisma.service_namesCreateWithoutServicesInput, Prisma.service_namesUncheckedCreateWithoutServicesInput>
  connectOrCreate?: Prisma.service_namesCreateOrConnectWithoutServicesInput
  upsert?: Prisma.service_namesUpsertWithoutServicesInput
  connect?: Prisma.service_namesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.service_namesUpdateToOneWithWhereWithoutServicesInput, Prisma.service_namesUpdateWithoutServicesInput>, Prisma.service_namesUncheckedUpdateWithoutServicesInput>
}

export type service_namesCreateNestedManyWithoutSpecializationsInput = {
  create?: Prisma.XOR<Prisma.service_namesCreateWithoutSpecializationsInput, Prisma.service_namesUncheckedCreateWithoutSpecializationsInput> | Prisma.service_namesCreateWithoutSpecializationsInput[] | Prisma.service_namesUncheckedCreateWithoutSpecializationsInput[]
  connectOrCreate?: Prisma.service_namesCreateOrConnectWithoutSpecializationsInput | Prisma.service_namesCreateOrConnectWithoutSpecializationsInput[]
  createMany?: Prisma.service_namesCreateManySpecializationsInputEnvelope
  connect?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
}

export type service_namesUncheckedCreateNestedManyWithoutSpecializationsInput = {
  create?: Prisma.XOR<Prisma.service_namesCreateWithoutSpecializationsInput, Prisma.service_namesUncheckedCreateWithoutSpecializationsInput> | Prisma.service_namesCreateWithoutSpecializationsInput[] | Prisma.service_namesUncheckedCreateWithoutSpecializationsInput[]
  connectOrCreate?: Prisma.service_namesCreateOrConnectWithoutSpecializationsInput | Prisma.service_namesCreateOrConnectWithoutSpecializationsInput[]
  createMany?: Prisma.service_namesCreateManySpecializationsInputEnvelope
  connect?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
}

export type service_namesUpdateManyWithoutSpecializationsNestedInput = {
  create?: Prisma.XOR<Prisma.service_namesCreateWithoutSpecializationsInput, Prisma.service_namesUncheckedCreateWithoutSpecializationsInput> | Prisma.service_namesCreateWithoutSpecializationsInput[] | Prisma.service_namesUncheckedCreateWithoutSpecializationsInput[]
  connectOrCreate?: Prisma.service_namesCreateOrConnectWithoutSpecializationsInput | Prisma.service_namesCreateOrConnectWithoutSpecializationsInput[]
  upsert?: Prisma.service_namesUpsertWithWhereUniqueWithoutSpecializationsInput | Prisma.service_namesUpsertWithWhereUniqueWithoutSpecializationsInput[]
  createMany?: Prisma.service_namesCreateManySpecializationsInputEnvelope
  set?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
  disconnect?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
  delete?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
  connect?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
  update?: Prisma.service_namesUpdateWithWhereUniqueWithoutSpecializationsInput | Prisma.service_namesUpdateWithWhereUniqueWithoutSpecializationsInput[]
  updateMany?: Prisma.service_namesUpdateManyWithWhereWithoutSpecializationsInput | Prisma.service_namesUpdateManyWithWhereWithoutSpecializationsInput[]
  deleteMany?: Prisma.service_namesScalarWhereInput | Prisma.service_namesScalarWhereInput[]
}

export type service_namesUncheckedUpdateManyWithoutSpecializationsNestedInput = {
  create?: Prisma.XOR<Prisma.service_namesCreateWithoutSpecializationsInput, Prisma.service_namesUncheckedCreateWithoutSpecializationsInput> | Prisma.service_namesCreateWithoutSpecializationsInput[] | Prisma.service_namesUncheckedCreateWithoutSpecializationsInput[]
  connectOrCreate?: Prisma.service_namesCreateOrConnectWithoutSpecializationsInput | Prisma.service_namesCreateOrConnectWithoutSpecializationsInput[]
  upsert?: Prisma.service_namesUpsertWithWhereUniqueWithoutSpecializationsInput | Prisma.service_namesUpsertWithWhereUniqueWithoutSpecializationsInput[]
  createMany?: Prisma.service_namesCreateManySpecializationsInputEnvelope
  set?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
  disconnect?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
  delete?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
  connect?: Prisma.service_namesWhereUniqueInput | Prisma.service_namesWhereUniqueInput[]
  update?: Prisma.service_namesUpdateWithWhereUniqueWithoutSpecializationsInput | Prisma.service_namesUpdateWithWhereUniqueWithoutSpecializationsInput[]
  updateMany?: Prisma.service_namesUpdateManyWithWhereWithoutSpecializationsInput | Prisma.service_namesUpdateManyWithWhereWithoutSpecializationsInput[]
  deleteMany?: Prisma.service_namesScalarWhereInput | Prisma.service_namesScalarWhereInput[]
}

export type service_namesCreateWithoutAppointmentsInput = {
  id?: string
  name: string
  specializations: Prisma.specializationsCreateNestedOneWithoutService_namesInput
  services?: Prisma.servicesCreateNestedManyWithoutService_namesInput
}

export type service_namesUncheckedCreateWithoutAppointmentsInput = {
  id?: string
  name: string
  specialization_id: string
  services?: Prisma.servicesUncheckedCreateNestedManyWithoutService_namesInput
}

export type service_namesCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.service_namesWhereUniqueInput
  create: Prisma.XOR<Prisma.service_namesCreateWithoutAppointmentsInput, Prisma.service_namesUncheckedCreateWithoutAppointmentsInput>
}

export type service_namesUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.service_namesUpdateWithoutAppointmentsInput, Prisma.service_namesUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.service_namesCreateWithoutAppointmentsInput, Prisma.service_namesUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.service_namesWhereInput
}

export type service_namesUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.service_namesWhereInput
  data: Prisma.XOR<Prisma.service_namesUpdateWithoutAppointmentsInput, Prisma.service_namesUncheckedUpdateWithoutAppointmentsInput>
}

export type service_namesUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specializations?: Prisma.specializationsUpdateOneRequiredWithoutService_namesNestedInput
  services?: Prisma.servicesUpdateManyWithoutService_namesNestedInput
}

export type service_namesUncheckedUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialization_id?: Prisma.StringFieldUpdateOperationsInput | string
  services?: Prisma.servicesUncheckedUpdateManyWithoutService_namesNestedInput
}

export type service_namesCreateWithoutServicesInput = {
  id?: string
  name: string
  appointments?: Prisma.appointmentsCreateNestedManyWithoutService_namesInput
  specializations: Prisma.specializationsCreateNestedOneWithoutService_namesInput
}

export type service_namesUncheckedCreateWithoutServicesInput = {
  id?: string
  name: string
  specialization_id: string
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutService_namesInput
}

export type service_namesCreateOrConnectWithoutServicesInput = {
  where: Prisma.service_namesWhereUniqueInput
  create: Prisma.XOR<Prisma.service_namesCreateWithoutServicesInput, Prisma.service_namesUncheckedCreateWithoutServicesInput>
}

export type service_namesUpsertWithoutServicesInput = {
  update: Prisma.XOR<Prisma.service_namesUpdateWithoutServicesInput, Prisma.service_namesUncheckedUpdateWithoutServicesInput>
  create: Prisma.XOR<Prisma.service_namesCreateWithoutServicesInput, Prisma.service_namesUncheckedCreateWithoutServicesInput>
  where?: Prisma.service_namesWhereInput
}

export type service_namesUpdateToOneWithWhereWithoutServicesInput = {
  where?: Prisma.service_namesWhereInput
  data: Prisma.XOR<Prisma.service_namesUpdateWithoutServicesInput, Prisma.service_namesUncheckedUpdateWithoutServicesInput>
}

export type service_namesUpdateWithoutServicesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  appointments?: Prisma.appointmentsUpdateManyWithoutService_namesNestedInput
  specializations?: Prisma.specializationsUpdateOneRequiredWithoutService_namesNestedInput
}

export type service_namesUncheckedUpdateWithoutServicesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  specialization_id?: Prisma.StringFieldUpdateOperationsInput | string
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutService_namesNestedInput
}

export type service_namesCreateWithoutSpecializationsInput = {
  id?: string
  name: string
  appointments?: Prisma.appointmentsCreateNestedManyWithoutService_namesInput
  services?: Prisma.servicesCreateNestedManyWithoutService_namesInput
}

export type service_namesUncheckedCreateWithoutSpecializationsInput = {
  id?: string
  name: string
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutService_namesInput
  services?: Prisma.servicesUncheckedCreateNestedManyWithoutService_namesInput
}

export type service_namesCreateOrConnectWithoutSpecializationsInput = {
  where: Prisma.service_namesWhereUniqueInput
  create: Prisma.XOR<Prisma.service_namesCreateWithoutSpecializationsInput, Prisma.service_namesUncheckedCreateWithoutSpecializationsInput>
}

export type service_namesCreateManySpecializationsInputEnvelope = {
  data: Prisma.service_namesCreateManySpecializationsInput | Prisma.service_namesCreateManySpecializationsInput[]
  skipDuplicates?: boolean
}

export type service_namesUpsertWithWhereUniqueWithoutSpecializationsInput = {
  where: Prisma.service_namesWhereUniqueInput
  update: Prisma.XOR<Prisma.service_namesUpdateWithoutSpecializationsInput, Prisma.service_namesUncheckedUpdateWithoutSpecializationsInput>
  create: Prisma.XOR<Prisma.service_namesCreateWithoutSpecializationsInput, Prisma.service_namesUncheckedCreateWithoutSpecializationsInput>
}

export type service_namesUpdateWithWhereUniqueWithoutSpecializationsInput = {
  where: Prisma.service_namesWhereUniqueInput
  data: Prisma.XOR<Prisma.service_namesUpdateWithoutSpecializationsInput, Prisma.service_namesUncheckedUpdateWithoutSpecializationsInput>
}

export type service_namesUpdateManyWithWhereWithoutSpecializationsInput = {
  where: Prisma.service_namesScalarWhereInput
  data: Prisma.XOR<Prisma.service_namesUpdateManyMutationInput, Prisma.service_namesUncheckedUpdateManyWithoutSpecializationsInput>
}

export type service_namesScalarWhereInput = {
  AND?: Prisma.service_namesScalarWhereInput | Prisma.service_namesScalarWhereInput[]
  OR?: Prisma.service_namesScalarWhereInput[]
  NOT?: Prisma.service_namesScalarWhereInput | Prisma.service_namesScalarWhereInput[]
  id?: Prisma.UuidFilter<"service_names"> | string
  name?: Prisma.StringFilter<"service_names"> | string
  specialization_id?: Prisma.UuidFilter<"service_names"> | string
}

export type service_namesCreateManySpecializationsInput = {
  id?: string
  name: string
}

export type service_namesUpdateWithoutSpecializationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  appointments?: Prisma.appointmentsUpdateManyWithoutService_namesNestedInput
  services?: Prisma.servicesUpdateManyWithoutService_namesNestedInput
}

export type service_namesUncheckedUpdateWithoutSpecializationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutService_namesNestedInput
  services?: Prisma.servicesUncheckedUpdateManyWithoutService_namesNestedInput
}

export type service_namesUncheckedUpdateManyWithoutSpecializationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type Service_namesCountOutputType
 */

export type Service_namesCountOutputType = {
  appointments: number
  services: number
}

export type Service_namesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | Service_namesCountOutputTypeCountAppointmentsArgs
  services?: boolean | Service_namesCountOutputTypeCountServicesArgs
}

/**
 * Service_namesCountOutputType without action
 */
export type Service_namesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Service_namesCountOutputType
   */
  select?: Prisma.Service_namesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Service_namesCountOutputType without action
 */
export type Service_namesCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.appointmentsWhereInput
}

/**
 * Service_namesCountOutputType without action
 */
export type Service_namesCountOutputTypeCountServicesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.servicesWhereInput
}


export type service_namesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  specialization_id?: boolean
  appointments?: boolean | Prisma.service_names$appointmentsArgs<ExtArgs>
  specializations?: boolean | Prisma.specializationsDefaultArgs<ExtArgs>
  services?: boolean | Prisma.service_names$servicesArgs<ExtArgs>
  _count?: boolean | Prisma.Service_namesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["service_names"]>

export type service_namesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  specialization_id?: boolean
  specializations?: boolean | Prisma.specializationsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["service_names"]>

export type service_namesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  specialization_id?: boolean
  specializations?: boolean | Prisma.specializationsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["service_names"]>

export type service_namesSelectScalar = {
  id?: boolean
  name?: boolean
  specialization_id?: boolean
}

export type service_namesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "specialization_id", ExtArgs["result"]["service_names"]>
export type service_namesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | Prisma.service_names$appointmentsArgs<ExtArgs>
  specializations?: boolean | Prisma.specializationsDefaultArgs<ExtArgs>
  services?: boolean | Prisma.service_names$servicesArgs<ExtArgs>
  _count?: boolean | Prisma.Service_namesCountOutputTypeDefaultArgs<ExtArgs>
}
export type service_namesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  specializations?: boolean | Prisma.specializationsDefaultArgs<ExtArgs>
}
export type service_namesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  specializations?: boolean | Prisma.specializationsDefaultArgs<ExtArgs>
}

export type $service_namesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "service_names"
  objects: {
    appointments: Prisma.$appointmentsPayload<ExtArgs>[]
    specializations: Prisma.$specializationsPayload<ExtArgs>
    services: Prisma.$servicesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    specialization_id: string
  }, ExtArgs["result"]["service_names"]>
  composites: {}
}

export type service_namesGetPayload<S extends boolean | null | undefined | service_namesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$service_namesPayload, S>

export type service_namesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<service_namesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Service_namesCountAggregateInputType | true
  }

export interface service_namesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['service_names'], meta: { name: 'service_names' } }
  /**
   * Find zero or one Service_names that matches the filter.
   * @param {service_namesFindUniqueArgs} args - Arguments to find a Service_names
   * @example
   * // Get one Service_names
   * const service_names = await prisma.service_names.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends service_namesFindUniqueArgs>(args: Prisma.SelectSubset<T, service_namesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__service_namesClient<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Service_names that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {service_namesFindUniqueOrThrowArgs} args - Arguments to find a Service_names
   * @example
   * // Get one Service_names
   * const service_names = await prisma.service_names.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends service_namesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, service_namesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__service_namesClient<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Service_names that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {service_namesFindFirstArgs} args - Arguments to find a Service_names
   * @example
   * // Get one Service_names
   * const service_names = await prisma.service_names.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends service_namesFindFirstArgs>(args?: Prisma.SelectSubset<T, service_namesFindFirstArgs<ExtArgs>>): Prisma.Prisma__service_namesClient<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Service_names that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {service_namesFindFirstOrThrowArgs} args - Arguments to find a Service_names
   * @example
   * // Get one Service_names
   * const service_names = await prisma.service_names.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends service_namesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, service_namesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__service_namesClient<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Service_names that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {service_namesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Service_names
   * const service_names = await prisma.service_names.findMany()
   * 
   * // Get first 10 Service_names
   * const service_names = await prisma.service_names.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const service_namesWithIdOnly = await prisma.service_names.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends service_namesFindManyArgs>(args?: Prisma.SelectSubset<T, service_namesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Service_names.
   * @param {service_namesCreateArgs} args - Arguments to create a Service_names.
   * @example
   * // Create one Service_names
   * const Service_names = await prisma.service_names.create({
   *   data: {
   *     // ... data to create a Service_names
   *   }
   * })
   * 
   */
  create<T extends service_namesCreateArgs>(args: Prisma.SelectSubset<T, service_namesCreateArgs<ExtArgs>>): Prisma.Prisma__service_namesClient<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Service_names.
   * @param {service_namesCreateManyArgs} args - Arguments to create many Service_names.
   * @example
   * // Create many Service_names
   * const service_names = await prisma.service_names.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends service_namesCreateManyArgs>(args?: Prisma.SelectSubset<T, service_namesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Service_names and returns the data saved in the database.
   * @param {service_namesCreateManyAndReturnArgs} args - Arguments to create many Service_names.
   * @example
   * // Create many Service_names
   * const service_names = await prisma.service_names.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Service_names and only return the `id`
   * const service_namesWithIdOnly = await prisma.service_names.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends service_namesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, service_namesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Service_names.
   * @param {service_namesDeleteArgs} args - Arguments to delete one Service_names.
   * @example
   * // Delete one Service_names
   * const Service_names = await prisma.service_names.delete({
   *   where: {
   *     // ... filter to delete one Service_names
   *   }
   * })
   * 
   */
  delete<T extends service_namesDeleteArgs>(args: Prisma.SelectSubset<T, service_namesDeleteArgs<ExtArgs>>): Prisma.Prisma__service_namesClient<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Service_names.
   * @param {service_namesUpdateArgs} args - Arguments to update one Service_names.
   * @example
   * // Update one Service_names
   * const service_names = await prisma.service_names.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends service_namesUpdateArgs>(args: Prisma.SelectSubset<T, service_namesUpdateArgs<ExtArgs>>): Prisma.Prisma__service_namesClient<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Service_names.
   * @param {service_namesDeleteManyArgs} args - Arguments to filter Service_names to delete.
   * @example
   * // Delete a few Service_names
   * const { count } = await prisma.service_names.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends service_namesDeleteManyArgs>(args?: Prisma.SelectSubset<T, service_namesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Service_names.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {service_namesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Service_names
   * const service_names = await prisma.service_names.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends service_namesUpdateManyArgs>(args: Prisma.SelectSubset<T, service_namesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Service_names and returns the data updated in the database.
   * @param {service_namesUpdateManyAndReturnArgs} args - Arguments to update many Service_names.
   * @example
   * // Update many Service_names
   * const service_names = await prisma.service_names.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Service_names and only return the `id`
   * const service_namesWithIdOnly = await prisma.service_names.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends service_namesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, service_namesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Service_names.
   * @param {service_namesUpsertArgs} args - Arguments to update or create a Service_names.
   * @example
   * // Update or create a Service_names
   * const service_names = await prisma.service_names.upsert({
   *   create: {
   *     // ... data to create a Service_names
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Service_names we want to update
   *   }
   * })
   */
  upsert<T extends service_namesUpsertArgs>(args: Prisma.SelectSubset<T, service_namesUpsertArgs<ExtArgs>>): Prisma.Prisma__service_namesClient<runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Service_names.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {service_namesCountArgs} args - Arguments to filter Service_names to count.
   * @example
   * // Count the number of Service_names
   * const count = await prisma.service_names.count({
   *   where: {
   *     // ... the filter for the Service_names we want to count
   *   }
   * })
  **/
  count<T extends service_namesCountArgs>(
    args?: Prisma.Subset<T, service_namesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Service_namesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Service_names.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Service_namesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Service_namesAggregateArgs>(args: Prisma.Subset<T, Service_namesAggregateArgs>): Prisma.PrismaPromise<GetService_namesAggregateType<T>>

  /**
   * Group by Service_names.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {service_namesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends service_namesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: service_namesGroupByArgs['orderBy'] }
      : { orderBy?: service_namesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, service_namesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetService_namesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the service_names model
 */
readonly fields: service_namesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for service_names.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__service_namesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  appointments<T extends Prisma.service_names$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.service_names$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  specializations<T extends Prisma.specializationsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.specializationsDefaultArgs<ExtArgs>>): Prisma.Prisma__specializationsClient<runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  services<T extends Prisma.service_names$servicesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.service_names$servicesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the service_names model
 */
export interface service_namesFieldRefs {
  readonly id: Prisma.FieldRef<"service_names", 'String'>
  readonly name: Prisma.FieldRef<"service_names", 'String'>
  readonly specialization_id: Prisma.FieldRef<"service_names", 'String'>
}
    

// Custom InputTypes
/**
 * service_names findUnique
 */
export type service_namesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  /**
   * Filter, which service_names to fetch.
   */
  where: Prisma.service_namesWhereUniqueInput
}

/**
 * service_names findUniqueOrThrow
 */
export type service_namesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  /**
   * Filter, which service_names to fetch.
   */
  where: Prisma.service_namesWhereUniqueInput
}

/**
 * service_names findFirst
 */
export type service_namesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  /**
   * Filter, which service_names to fetch.
   */
  where?: Prisma.service_namesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of service_names to fetch.
   */
  orderBy?: Prisma.service_namesOrderByWithRelationInput | Prisma.service_namesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for service_names.
   */
  cursor?: Prisma.service_namesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` service_names from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` service_names.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of service_names.
   */
  distinct?: Prisma.Service_namesScalarFieldEnum | Prisma.Service_namesScalarFieldEnum[]
}

/**
 * service_names findFirstOrThrow
 */
export type service_namesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  /**
   * Filter, which service_names to fetch.
   */
  where?: Prisma.service_namesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of service_names to fetch.
   */
  orderBy?: Prisma.service_namesOrderByWithRelationInput | Prisma.service_namesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for service_names.
   */
  cursor?: Prisma.service_namesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` service_names from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` service_names.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of service_names.
   */
  distinct?: Prisma.Service_namesScalarFieldEnum | Prisma.Service_namesScalarFieldEnum[]
}

/**
 * service_names findMany
 */
export type service_namesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  /**
   * Filter, which service_names to fetch.
   */
  where?: Prisma.service_namesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of service_names to fetch.
   */
  orderBy?: Prisma.service_namesOrderByWithRelationInput | Prisma.service_namesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing service_names.
   */
  cursor?: Prisma.service_namesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` service_names from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` service_names.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of service_names.
   */
  distinct?: Prisma.Service_namesScalarFieldEnum | Prisma.Service_namesScalarFieldEnum[]
}

/**
 * service_names create
 */
export type service_namesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  /**
   * The data needed to create a service_names.
   */
  data: Prisma.XOR<Prisma.service_namesCreateInput, Prisma.service_namesUncheckedCreateInput>
}

/**
 * service_names createMany
 */
export type service_namesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many service_names.
   */
  data: Prisma.service_namesCreateManyInput | Prisma.service_namesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * service_names createManyAndReturn
 */
export type service_namesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * The data used to create many service_names.
   */
  data: Prisma.service_namesCreateManyInput | Prisma.service_namesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * service_names update
 */
export type service_namesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  /**
   * The data needed to update a service_names.
   */
  data: Prisma.XOR<Prisma.service_namesUpdateInput, Prisma.service_namesUncheckedUpdateInput>
  /**
   * Choose, which service_names to update.
   */
  where: Prisma.service_namesWhereUniqueInput
}

/**
 * service_names updateMany
 */
export type service_namesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update service_names.
   */
  data: Prisma.XOR<Prisma.service_namesUpdateManyMutationInput, Prisma.service_namesUncheckedUpdateManyInput>
  /**
   * Filter which service_names to update
   */
  where?: Prisma.service_namesWhereInput
  /**
   * Limit how many service_names to update.
   */
  limit?: number
}

/**
 * service_names updateManyAndReturn
 */
export type service_namesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * The data used to update service_names.
   */
  data: Prisma.XOR<Prisma.service_namesUpdateManyMutationInput, Prisma.service_namesUncheckedUpdateManyInput>
  /**
   * Filter which service_names to update
   */
  where?: Prisma.service_namesWhereInput
  /**
   * Limit how many service_names to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * service_names upsert
 */
export type service_namesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  /**
   * The filter to search for the service_names to update in case it exists.
   */
  where: Prisma.service_namesWhereUniqueInput
  /**
   * In case the service_names found by the `where` argument doesn't exist, create a new service_names with this data.
   */
  create: Prisma.XOR<Prisma.service_namesCreateInput, Prisma.service_namesUncheckedCreateInput>
  /**
   * In case the service_names was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.service_namesUpdateInput, Prisma.service_namesUncheckedUpdateInput>
}

/**
 * service_names delete
 */
export type service_namesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  /**
   * Filter which service_names to delete.
   */
  where: Prisma.service_namesWhereUniqueInput
}

/**
 * service_names deleteMany
 */
export type service_namesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which service_names to delete
   */
  where?: Prisma.service_namesWhereInput
  /**
   * Limit how many service_names to delete.
   */
  limit?: number
}

/**
 * service_names.appointments
 */
export type service_names$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  where?: Prisma.appointmentsWhereInput
  orderBy?: Prisma.appointmentsOrderByWithRelationInput | Prisma.appointmentsOrderByWithRelationInput[]
  cursor?: Prisma.appointmentsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentsScalarFieldEnum | Prisma.AppointmentsScalarFieldEnum[]
}

/**
 * service_names.services
 */
export type service_names$servicesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  where?: Prisma.servicesWhereInput
  orderBy?: Prisma.servicesOrderByWithRelationInput | Prisma.servicesOrderByWithRelationInput[]
  cursor?: Prisma.servicesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ServicesScalarFieldEnum | Prisma.ServicesScalarFieldEnum[]
}

/**
 * service_names without action
 */
export type service_namesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
}
