
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `specialists` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model specialists
 * 
 */
export type specialistsModel = runtime.Types.Result.DefaultSelection<Prisma.$specialistsPayload>

export type AggregateSpecialists = {
  _count: SpecialistsCountAggregateOutputType | null
  _min: SpecialistsMinAggregateOutputType | null
  _max: SpecialistsMaxAggregateOutputType | null
}

export type SpecialistsMinAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phone: string | null
  birthdate: Date | null
  cpf: string | null
  cnpj: string | null
}

export type SpecialistsMaxAggregateOutputType = {
  id: string | null
  name: string | null
  email: string | null
  phone: string | null
  birthdate: Date | null
  cpf: string | null
  cnpj: string | null
}

export type SpecialistsCountAggregateOutputType = {
  id: number
  name: number
  email: number
  phone: number
  birthdate: number
  cpf: number
  cnpj: number
  _all: number
}


export type SpecialistsMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  birthdate?: true
  cpf?: true
  cnpj?: true
}

export type SpecialistsMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  birthdate?: true
  cpf?: true
  cnpj?: true
}

export type SpecialistsCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  phone?: true
  birthdate?: true
  cpf?: true
  cnpj?: true
  _all?: true
}

export type SpecialistsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which specialists to aggregate.
   */
  where?: Prisma.specialistsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of specialists to fetch.
   */
  orderBy?: Prisma.specialistsOrderByWithRelationInput | Prisma.specialistsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.specialistsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` specialists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` specialists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned specialists
  **/
  _count?: true | SpecialistsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SpecialistsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SpecialistsMaxAggregateInputType
}

export type GetSpecialistsAggregateType<T extends SpecialistsAggregateArgs> = {
      [P in keyof T & keyof AggregateSpecialists]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSpecialists[P]>
    : Prisma.GetScalarType<T[P], AggregateSpecialists[P]>
}




export type specialistsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.specialistsWhereInput
  orderBy?: Prisma.specialistsOrderByWithAggregationInput | Prisma.specialistsOrderByWithAggregationInput[]
  by: Prisma.SpecialistsScalarFieldEnum[] | Prisma.SpecialistsScalarFieldEnum
  having?: Prisma.specialistsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SpecialistsCountAggregateInputType | true
  _min?: SpecialistsMinAggregateInputType
  _max?: SpecialistsMaxAggregateInputType
}

export type SpecialistsGroupByOutputType = {
  id: string
  name: string
  email: string
  phone: string
  birthdate: Date
  cpf: string
  cnpj: string | null
  _count: SpecialistsCountAggregateOutputType | null
  _min: SpecialistsMinAggregateOutputType | null
  _max: SpecialistsMaxAggregateOutputType | null
}

export type GetSpecialistsGroupByPayload<T extends specialistsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SpecialistsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SpecialistsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SpecialistsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SpecialistsGroupByOutputType[P]>
      }
    >
  >



export type specialistsWhereInput = {
  AND?: Prisma.specialistsWhereInput | Prisma.specialistsWhereInput[]
  OR?: Prisma.specialistsWhereInput[]
  NOT?: Prisma.specialistsWhereInput | Prisma.specialistsWhereInput[]
  id?: Prisma.UuidFilter<"specialists"> | string
  name?: Prisma.StringFilter<"specialists"> | string
  email?: Prisma.StringFilter<"specialists"> | string
  phone?: Prisma.StringFilter<"specialists"> | string
  birthdate?: Prisma.DateTimeFilter<"specialists"> | Date | string
  cpf?: Prisma.StringFilter<"specialists"> | string
  cnpj?: Prisma.StringNullableFilter<"specialists"> | string | null
  appointments?: Prisma.AppointmentsListRelationFilter
  services?: Prisma.ServicesListRelationFilter
  specialist_hours?: Prisma.Specialist_hoursListRelationFilter
}

export type specialistsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrderInput | Prisma.SortOrder
  appointments?: Prisma.appointmentsOrderByRelationAggregateInput
  services?: Prisma.servicesOrderByRelationAggregateInput
  specialist_hours?: Prisma.specialist_hoursOrderByRelationAggregateInput
}

export type specialistsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  email?: string
  AND?: Prisma.specialistsWhereInput | Prisma.specialistsWhereInput[]
  OR?: Prisma.specialistsWhereInput[]
  NOT?: Prisma.specialistsWhereInput | Prisma.specialistsWhereInput[]
  name?: Prisma.StringFilter<"specialists"> | string
  phone?: Prisma.StringFilter<"specialists"> | string
  birthdate?: Prisma.DateTimeFilter<"specialists"> | Date | string
  cpf?: Prisma.StringFilter<"specialists"> | string
  cnpj?: Prisma.StringNullableFilter<"specialists"> | string | null
  appointments?: Prisma.AppointmentsListRelationFilter
  services?: Prisma.ServicesListRelationFilter
  specialist_hours?: Prisma.Specialist_hoursListRelationFilter
}, "id" | "email">

export type specialistsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.specialistsCountOrderByAggregateInput
  _max?: Prisma.specialistsMaxOrderByAggregateInput
  _min?: Prisma.specialistsMinOrderByAggregateInput
}

export type specialistsScalarWhereWithAggregatesInput = {
  AND?: Prisma.specialistsScalarWhereWithAggregatesInput | Prisma.specialistsScalarWhereWithAggregatesInput[]
  OR?: Prisma.specialistsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.specialistsScalarWhereWithAggregatesInput | Prisma.specialistsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"specialists"> | string
  name?: Prisma.StringWithAggregatesFilter<"specialists"> | string
  email?: Prisma.StringWithAggregatesFilter<"specialists"> | string
  phone?: Prisma.StringWithAggregatesFilter<"specialists"> | string
  birthdate?: Prisma.DateTimeWithAggregatesFilter<"specialists"> | Date | string
  cpf?: Prisma.StringWithAggregatesFilter<"specialists"> | string
  cnpj?: Prisma.StringNullableWithAggregatesFilter<"specialists"> | string | null
}

export type specialistsCreateInput = {
  id?: string
  name: string
  email: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
  appointments?: Prisma.appointmentsCreateNestedManyWithoutSpecialistsInput
  services?: Prisma.servicesCreateNestedManyWithoutSpecialistsInput
  specialist_hours?: Prisma.specialist_hoursCreateNestedManyWithoutSpecialistsInput
}

export type specialistsUncheckedCreateInput = {
  id?: string
  name: string
  email: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutSpecialistsInput
  services?: Prisma.servicesUncheckedCreateNestedManyWithoutSpecialistsInput
  specialist_hours?: Prisma.specialist_hoursUncheckedCreateNestedManyWithoutSpecialistsInput
}

export type specialistsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointments?: Prisma.appointmentsUpdateManyWithoutSpecialistsNestedInput
  services?: Prisma.servicesUpdateManyWithoutSpecialistsNestedInput
  specialist_hours?: Prisma.specialist_hoursUpdateManyWithoutSpecialistsNestedInput
}

export type specialistsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutSpecialistsNestedInput
  services?: Prisma.servicesUncheckedUpdateManyWithoutSpecialistsNestedInput
  specialist_hours?: Prisma.specialist_hoursUncheckedUpdateManyWithoutSpecialistsNestedInput
}

export type specialistsCreateManyInput = {
  id?: string
  name: string
  email: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
}

export type specialistsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type specialistsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type SpecialistsScalarRelationFilter = {
  is?: Prisma.specialistsWhereInput
  isNot?: Prisma.specialistsWhereInput
}

export type specialistsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrder
}

export type specialistsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrder
}

export type specialistsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  birthdate?: Prisma.SortOrder
  cpf?: Prisma.SortOrder
  cnpj?: Prisma.SortOrder
}

export type specialistsCreateNestedOneWithoutAppointmentsInput = {
  create?: Prisma.XOR<Prisma.specialistsCreateWithoutAppointmentsInput, Prisma.specialistsUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.specialistsCreateOrConnectWithoutAppointmentsInput
  connect?: Prisma.specialistsWhereUniqueInput
}

export type specialistsUpdateOneRequiredWithoutAppointmentsNestedInput = {
  create?: Prisma.XOR<Prisma.specialistsCreateWithoutAppointmentsInput, Prisma.specialistsUncheckedCreateWithoutAppointmentsInput>
  connectOrCreate?: Prisma.specialistsCreateOrConnectWithoutAppointmentsInput
  upsert?: Prisma.specialistsUpsertWithoutAppointmentsInput
  connect?: Prisma.specialistsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.specialistsUpdateToOneWithWhereWithoutAppointmentsInput, Prisma.specialistsUpdateWithoutAppointmentsInput>, Prisma.specialistsUncheckedUpdateWithoutAppointmentsInput>
}

export type specialistsCreateNestedOneWithoutServicesInput = {
  create?: Prisma.XOR<Prisma.specialistsCreateWithoutServicesInput, Prisma.specialistsUncheckedCreateWithoutServicesInput>
  connectOrCreate?: Prisma.specialistsCreateOrConnectWithoutServicesInput
  connect?: Prisma.specialistsWhereUniqueInput
}

export type specialistsUpdateOneRequiredWithoutServicesNestedInput = {
  create?: Prisma.XOR<Prisma.specialistsCreateWithoutServicesInput, Prisma.specialistsUncheckedCreateWithoutServicesInput>
  connectOrCreate?: Prisma.specialistsCreateOrConnectWithoutServicesInput
  upsert?: Prisma.specialistsUpsertWithoutServicesInput
  connect?: Prisma.specialistsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.specialistsUpdateToOneWithWhereWithoutServicesInput, Prisma.specialistsUpdateWithoutServicesInput>, Prisma.specialistsUncheckedUpdateWithoutServicesInput>
}

export type specialistsCreateNestedOneWithoutSpecialist_hoursInput = {
  create?: Prisma.XOR<Prisma.specialistsCreateWithoutSpecialist_hoursInput, Prisma.specialistsUncheckedCreateWithoutSpecialist_hoursInput>
  connectOrCreate?: Prisma.specialistsCreateOrConnectWithoutSpecialist_hoursInput
  connect?: Prisma.specialistsWhereUniqueInput
}

export type specialistsUpdateOneRequiredWithoutSpecialist_hoursNestedInput = {
  create?: Prisma.XOR<Prisma.specialistsCreateWithoutSpecialist_hoursInput, Prisma.specialistsUncheckedCreateWithoutSpecialist_hoursInput>
  connectOrCreate?: Prisma.specialistsCreateOrConnectWithoutSpecialist_hoursInput
  upsert?: Prisma.specialistsUpsertWithoutSpecialist_hoursInput
  connect?: Prisma.specialistsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.specialistsUpdateToOneWithWhereWithoutSpecialist_hoursInput, Prisma.specialistsUpdateWithoutSpecialist_hoursInput>, Prisma.specialistsUncheckedUpdateWithoutSpecialist_hoursInput>
}

export type specialistsCreateWithoutAppointmentsInput = {
  id?: string
  name: string
  email: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
  services?: Prisma.servicesCreateNestedManyWithoutSpecialistsInput
  specialist_hours?: Prisma.specialist_hoursCreateNestedManyWithoutSpecialistsInput
}

export type specialistsUncheckedCreateWithoutAppointmentsInput = {
  id?: string
  name: string
  email: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
  services?: Prisma.servicesUncheckedCreateNestedManyWithoutSpecialistsInput
  specialist_hours?: Prisma.specialist_hoursUncheckedCreateNestedManyWithoutSpecialistsInput
}

export type specialistsCreateOrConnectWithoutAppointmentsInput = {
  where: Prisma.specialistsWhereUniqueInput
  create: Prisma.XOR<Prisma.specialistsCreateWithoutAppointmentsInput, Prisma.specialistsUncheckedCreateWithoutAppointmentsInput>
}

export type specialistsUpsertWithoutAppointmentsInput = {
  update: Prisma.XOR<Prisma.specialistsUpdateWithoutAppointmentsInput, Prisma.specialistsUncheckedUpdateWithoutAppointmentsInput>
  create: Prisma.XOR<Prisma.specialistsCreateWithoutAppointmentsInput, Prisma.specialistsUncheckedCreateWithoutAppointmentsInput>
  where?: Prisma.specialistsWhereInput
}

export type specialistsUpdateToOneWithWhereWithoutAppointmentsInput = {
  where?: Prisma.specialistsWhereInput
  data: Prisma.XOR<Prisma.specialistsUpdateWithoutAppointmentsInput, Prisma.specialistsUncheckedUpdateWithoutAppointmentsInput>
}

export type specialistsUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  services?: Prisma.servicesUpdateManyWithoutSpecialistsNestedInput
  specialist_hours?: Prisma.specialist_hoursUpdateManyWithoutSpecialistsNestedInput
}

export type specialistsUncheckedUpdateWithoutAppointmentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  services?: Prisma.servicesUncheckedUpdateManyWithoutSpecialistsNestedInput
  specialist_hours?: Prisma.specialist_hoursUncheckedUpdateManyWithoutSpecialistsNestedInput
}

export type specialistsCreateWithoutServicesInput = {
  id?: string
  name: string
  email: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
  appointments?: Prisma.appointmentsCreateNestedManyWithoutSpecialistsInput
  specialist_hours?: Prisma.specialist_hoursCreateNestedManyWithoutSpecialistsInput
}

export type specialistsUncheckedCreateWithoutServicesInput = {
  id?: string
  name: string
  email: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutSpecialistsInput
  specialist_hours?: Prisma.specialist_hoursUncheckedCreateNestedManyWithoutSpecialistsInput
}

export type specialistsCreateOrConnectWithoutServicesInput = {
  where: Prisma.specialistsWhereUniqueInput
  create: Prisma.XOR<Prisma.specialistsCreateWithoutServicesInput, Prisma.specialistsUncheckedCreateWithoutServicesInput>
}

export type specialistsUpsertWithoutServicesInput = {
  update: Prisma.XOR<Prisma.specialistsUpdateWithoutServicesInput, Prisma.specialistsUncheckedUpdateWithoutServicesInput>
  create: Prisma.XOR<Prisma.specialistsCreateWithoutServicesInput, Prisma.specialistsUncheckedCreateWithoutServicesInput>
  where?: Prisma.specialistsWhereInput
}

export type specialistsUpdateToOneWithWhereWithoutServicesInput = {
  where?: Prisma.specialistsWhereInput
  data: Prisma.XOR<Prisma.specialistsUpdateWithoutServicesInput, Prisma.specialistsUncheckedUpdateWithoutServicesInput>
}

export type specialistsUpdateWithoutServicesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointments?: Prisma.appointmentsUpdateManyWithoutSpecialistsNestedInput
  specialist_hours?: Prisma.specialist_hoursUpdateManyWithoutSpecialistsNestedInput
}

export type specialistsUncheckedUpdateWithoutServicesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutSpecialistsNestedInput
  specialist_hours?: Prisma.specialist_hoursUncheckedUpdateManyWithoutSpecialistsNestedInput
}

export type specialistsCreateWithoutSpecialist_hoursInput = {
  id?: string
  name: string
  email: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
  appointments?: Prisma.appointmentsCreateNestedManyWithoutSpecialistsInput
  services?: Prisma.servicesCreateNestedManyWithoutSpecialistsInput
}

export type specialistsUncheckedCreateWithoutSpecialist_hoursInput = {
  id?: string
  name: string
  email: string
  phone: string
  birthdate: Date | string
  cpf: string
  cnpj?: string | null
  appointments?: Prisma.appointmentsUncheckedCreateNestedManyWithoutSpecialistsInput
  services?: Prisma.servicesUncheckedCreateNestedManyWithoutSpecialistsInput
}

export type specialistsCreateOrConnectWithoutSpecialist_hoursInput = {
  where: Prisma.specialistsWhereUniqueInput
  create: Prisma.XOR<Prisma.specialistsCreateWithoutSpecialist_hoursInput, Prisma.specialistsUncheckedCreateWithoutSpecialist_hoursInput>
}

export type specialistsUpsertWithoutSpecialist_hoursInput = {
  update: Prisma.XOR<Prisma.specialistsUpdateWithoutSpecialist_hoursInput, Prisma.specialistsUncheckedUpdateWithoutSpecialist_hoursInput>
  create: Prisma.XOR<Prisma.specialistsCreateWithoutSpecialist_hoursInput, Prisma.specialistsUncheckedCreateWithoutSpecialist_hoursInput>
  where?: Prisma.specialistsWhereInput
}

export type specialistsUpdateToOneWithWhereWithoutSpecialist_hoursInput = {
  where?: Prisma.specialistsWhereInput
  data: Prisma.XOR<Prisma.specialistsUpdateWithoutSpecialist_hoursInput, Prisma.specialistsUncheckedUpdateWithoutSpecialist_hoursInput>
}

export type specialistsUpdateWithoutSpecialist_hoursInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointments?: Prisma.appointmentsUpdateManyWithoutSpecialistsNestedInput
  services?: Prisma.servicesUpdateManyWithoutSpecialistsNestedInput
}

export type specialistsUncheckedUpdateWithoutSpecialist_hoursInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.StringFieldUpdateOperationsInput | string
  birthdate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cpf?: Prisma.StringFieldUpdateOperationsInput | string
  cnpj?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  appointments?: Prisma.appointmentsUncheckedUpdateManyWithoutSpecialistsNestedInput
  services?: Prisma.servicesUncheckedUpdateManyWithoutSpecialistsNestedInput
}


/**
 * Count Type SpecialistsCountOutputType
 */

export type SpecialistsCountOutputType = {
  appointments: number
  services: number
  specialist_hours: number
}

export type SpecialistsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | SpecialistsCountOutputTypeCountAppointmentsArgs
  services?: boolean | SpecialistsCountOutputTypeCountServicesArgs
  specialist_hours?: boolean | SpecialistsCountOutputTypeCountSpecialist_hoursArgs
}

/**
 * SpecialistsCountOutputType without action
 */
export type SpecialistsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpecialistsCountOutputType
   */
  select?: Prisma.SpecialistsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SpecialistsCountOutputType without action
 */
export type SpecialistsCountOutputTypeCountAppointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.appointmentsWhereInput
}

/**
 * SpecialistsCountOutputType without action
 */
export type SpecialistsCountOutputTypeCountServicesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.servicesWhereInput
}

/**
 * SpecialistsCountOutputType without action
 */
export type SpecialistsCountOutputTypeCountSpecialist_hoursArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.specialist_hoursWhereInput
}


export type specialistsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  birthdate?: boolean
  cpf?: boolean
  cnpj?: boolean
  appointments?: boolean | Prisma.specialists$appointmentsArgs<ExtArgs>
  services?: boolean | Prisma.specialists$servicesArgs<ExtArgs>
  specialist_hours?: boolean | Prisma.specialists$specialist_hoursArgs<ExtArgs>
  _count?: boolean | Prisma.SpecialistsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["specialists"]>

export type specialistsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  birthdate?: boolean
  cpf?: boolean
  cnpj?: boolean
}, ExtArgs["result"]["specialists"]>

export type specialistsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  birthdate?: boolean
  cpf?: boolean
  cnpj?: boolean
}, ExtArgs["result"]["specialists"]>

export type specialistsSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
  phone?: boolean
  birthdate?: boolean
  cpf?: boolean
  cnpj?: boolean
}

export type specialistsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email" | "phone" | "birthdate" | "cpf" | "cnpj", ExtArgs["result"]["specialists"]>
export type specialistsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointments?: boolean | Prisma.specialists$appointmentsArgs<ExtArgs>
  services?: boolean | Prisma.specialists$servicesArgs<ExtArgs>
  specialist_hours?: boolean | Prisma.specialists$specialist_hoursArgs<ExtArgs>
  _count?: boolean | Prisma.SpecialistsCountOutputTypeDefaultArgs<ExtArgs>
}
export type specialistsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type specialistsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $specialistsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "specialists"
  objects: {
    appointments: Prisma.$appointmentsPayload<ExtArgs>[]
    services: Prisma.$servicesPayload<ExtArgs>[]
    specialist_hours: Prisma.$specialist_hoursPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    email: string
    phone: string
    birthdate: Date
    cpf: string
    cnpj: string | null
  }, ExtArgs["result"]["specialists"]>
  composites: {}
}

export type specialistsGetPayload<S extends boolean | null | undefined | specialistsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$specialistsPayload, S>

export type specialistsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<specialistsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SpecialistsCountAggregateInputType | true
  }

export interface specialistsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['specialists'], meta: { name: 'specialists' } }
  /**
   * Find zero or one Specialists that matches the filter.
   * @param {specialistsFindUniqueArgs} args - Arguments to find a Specialists
   * @example
   * // Get one Specialists
   * const specialists = await prisma.specialists.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends specialistsFindUniqueArgs>(args: Prisma.SelectSubset<T, specialistsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__specialistsClient<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Specialists that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {specialistsFindUniqueOrThrowArgs} args - Arguments to find a Specialists
   * @example
   * // Get one Specialists
   * const specialists = await prisma.specialists.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends specialistsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, specialistsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__specialistsClient<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Specialists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specialistsFindFirstArgs} args - Arguments to find a Specialists
   * @example
   * // Get one Specialists
   * const specialists = await prisma.specialists.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends specialistsFindFirstArgs>(args?: Prisma.SelectSubset<T, specialistsFindFirstArgs<ExtArgs>>): Prisma.Prisma__specialistsClient<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Specialists that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specialistsFindFirstOrThrowArgs} args - Arguments to find a Specialists
   * @example
   * // Get one Specialists
   * const specialists = await prisma.specialists.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends specialistsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, specialistsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__specialistsClient<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Specialists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specialistsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Specialists
   * const specialists = await prisma.specialists.findMany()
   * 
   * // Get first 10 Specialists
   * const specialists = await prisma.specialists.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const specialistsWithIdOnly = await prisma.specialists.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends specialistsFindManyArgs>(args?: Prisma.SelectSubset<T, specialistsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Specialists.
   * @param {specialistsCreateArgs} args - Arguments to create a Specialists.
   * @example
   * // Create one Specialists
   * const Specialists = await prisma.specialists.create({
   *   data: {
   *     // ... data to create a Specialists
   *   }
   * })
   * 
   */
  create<T extends specialistsCreateArgs>(args: Prisma.SelectSubset<T, specialistsCreateArgs<ExtArgs>>): Prisma.Prisma__specialistsClient<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Specialists.
   * @param {specialistsCreateManyArgs} args - Arguments to create many Specialists.
   * @example
   * // Create many Specialists
   * const specialists = await prisma.specialists.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends specialistsCreateManyArgs>(args?: Prisma.SelectSubset<T, specialistsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Specialists and returns the data saved in the database.
   * @param {specialistsCreateManyAndReturnArgs} args - Arguments to create many Specialists.
   * @example
   * // Create many Specialists
   * const specialists = await prisma.specialists.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Specialists and only return the `id`
   * const specialistsWithIdOnly = await prisma.specialists.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends specialistsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, specialistsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Specialists.
   * @param {specialistsDeleteArgs} args - Arguments to delete one Specialists.
   * @example
   * // Delete one Specialists
   * const Specialists = await prisma.specialists.delete({
   *   where: {
   *     // ... filter to delete one Specialists
   *   }
   * })
   * 
   */
  delete<T extends specialistsDeleteArgs>(args: Prisma.SelectSubset<T, specialistsDeleteArgs<ExtArgs>>): Prisma.Prisma__specialistsClient<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Specialists.
   * @param {specialistsUpdateArgs} args - Arguments to update one Specialists.
   * @example
   * // Update one Specialists
   * const specialists = await prisma.specialists.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends specialistsUpdateArgs>(args: Prisma.SelectSubset<T, specialistsUpdateArgs<ExtArgs>>): Prisma.Prisma__specialistsClient<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Specialists.
   * @param {specialistsDeleteManyArgs} args - Arguments to filter Specialists to delete.
   * @example
   * // Delete a few Specialists
   * const { count } = await prisma.specialists.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends specialistsDeleteManyArgs>(args?: Prisma.SelectSubset<T, specialistsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Specialists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specialistsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Specialists
   * const specialists = await prisma.specialists.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends specialistsUpdateManyArgs>(args: Prisma.SelectSubset<T, specialistsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Specialists and returns the data updated in the database.
   * @param {specialistsUpdateManyAndReturnArgs} args - Arguments to update many Specialists.
   * @example
   * // Update many Specialists
   * const specialists = await prisma.specialists.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Specialists and only return the `id`
   * const specialistsWithIdOnly = await prisma.specialists.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends specialistsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, specialistsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Specialists.
   * @param {specialistsUpsertArgs} args - Arguments to update or create a Specialists.
   * @example
   * // Update or create a Specialists
   * const specialists = await prisma.specialists.upsert({
   *   create: {
   *     // ... data to create a Specialists
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Specialists we want to update
   *   }
   * })
   */
  upsert<T extends specialistsUpsertArgs>(args: Prisma.SelectSubset<T, specialistsUpsertArgs<ExtArgs>>): Prisma.Prisma__specialistsClient<runtime.Types.Result.GetResult<Prisma.$specialistsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Specialists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specialistsCountArgs} args - Arguments to filter Specialists to count.
   * @example
   * // Count the number of Specialists
   * const count = await prisma.specialists.count({
   *   where: {
   *     // ... the filter for the Specialists we want to count
   *   }
   * })
  **/
  count<T extends specialistsCountArgs>(
    args?: Prisma.Subset<T, specialistsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SpecialistsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Specialists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpecialistsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SpecialistsAggregateArgs>(args: Prisma.Subset<T, SpecialistsAggregateArgs>): Prisma.PrismaPromise<GetSpecialistsAggregateType<T>>

  /**
   * Group by Specialists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specialistsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends specialistsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: specialistsGroupByArgs['orderBy'] }
      : { orderBy?: specialistsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, specialistsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSpecialistsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the specialists model
 */
readonly fields: specialistsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for specialists.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__specialistsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  appointments<T extends Prisma.specialists$appointmentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.specialists$appointmentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$appointmentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  services<T extends Prisma.specialists$servicesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.specialists$servicesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$servicesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  specialist_hours<T extends Prisma.specialists$specialist_hoursArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.specialists$specialist_hoursArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$specialist_hoursPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the specialists model
 */
export interface specialistsFieldRefs {
  readonly id: Prisma.FieldRef<"specialists", 'String'>
  readonly name: Prisma.FieldRef<"specialists", 'String'>
  readonly email: Prisma.FieldRef<"specialists", 'String'>
  readonly phone: Prisma.FieldRef<"specialists", 'String'>
  readonly birthdate: Prisma.FieldRef<"specialists", 'DateTime'>
  readonly cpf: Prisma.FieldRef<"specialists", 'String'>
  readonly cnpj: Prisma.FieldRef<"specialists", 'String'>
}
    

// Custom InputTypes
/**
 * specialists findUnique
 */
export type specialistsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
  /**
   * Filter, which specialists to fetch.
   */
  where: Prisma.specialistsWhereUniqueInput
}

/**
 * specialists findUniqueOrThrow
 */
export type specialistsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
  /**
   * Filter, which specialists to fetch.
   */
  where: Prisma.specialistsWhereUniqueInput
}

/**
 * specialists findFirst
 */
export type specialistsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
  /**
   * Filter, which specialists to fetch.
   */
  where?: Prisma.specialistsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of specialists to fetch.
   */
  orderBy?: Prisma.specialistsOrderByWithRelationInput | Prisma.specialistsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for specialists.
   */
  cursor?: Prisma.specialistsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` specialists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` specialists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of specialists.
   */
  distinct?: Prisma.SpecialistsScalarFieldEnum | Prisma.SpecialistsScalarFieldEnum[]
}

/**
 * specialists findFirstOrThrow
 */
export type specialistsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
  /**
   * Filter, which specialists to fetch.
   */
  where?: Prisma.specialistsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of specialists to fetch.
   */
  orderBy?: Prisma.specialistsOrderByWithRelationInput | Prisma.specialistsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for specialists.
   */
  cursor?: Prisma.specialistsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` specialists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` specialists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of specialists.
   */
  distinct?: Prisma.SpecialistsScalarFieldEnum | Prisma.SpecialistsScalarFieldEnum[]
}

/**
 * specialists findMany
 */
export type specialistsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
  /**
   * Filter, which specialists to fetch.
   */
  where?: Prisma.specialistsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of specialists to fetch.
   */
  orderBy?: Prisma.specialistsOrderByWithRelationInput | Prisma.specialistsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing specialists.
   */
  cursor?: Prisma.specialistsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` specialists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` specialists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of specialists.
   */
  distinct?: Prisma.SpecialistsScalarFieldEnum | Prisma.SpecialistsScalarFieldEnum[]
}

/**
 * specialists create
 */
export type specialistsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
  /**
   * The data needed to create a specialists.
   */
  data: Prisma.XOR<Prisma.specialistsCreateInput, Prisma.specialistsUncheckedCreateInput>
}

/**
 * specialists createMany
 */
export type specialistsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many specialists.
   */
  data: Prisma.specialistsCreateManyInput | Prisma.specialistsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * specialists createManyAndReturn
 */
export type specialistsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * The data used to create many specialists.
   */
  data: Prisma.specialistsCreateManyInput | Prisma.specialistsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * specialists update
 */
export type specialistsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
  /**
   * The data needed to update a specialists.
   */
  data: Prisma.XOR<Prisma.specialistsUpdateInput, Prisma.specialistsUncheckedUpdateInput>
  /**
   * Choose, which specialists to update.
   */
  where: Prisma.specialistsWhereUniqueInput
}

/**
 * specialists updateMany
 */
export type specialistsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update specialists.
   */
  data: Prisma.XOR<Prisma.specialistsUpdateManyMutationInput, Prisma.specialistsUncheckedUpdateManyInput>
  /**
   * Filter which specialists to update
   */
  where?: Prisma.specialistsWhereInput
  /**
   * Limit how many specialists to update.
   */
  limit?: number
}

/**
 * specialists updateManyAndReturn
 */
export type specialistsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * The data used to update specialists.
   */
  data: Prisma.XOR<Prisma.specialistsUpdateManyMutationInput, Prisma.specialistsUncheckedUpdateManyInput>
  /**
   * Filter which specialists to update
   */
  where?: Prisma.specialistsWhereInput
  /**
   * Limit how many specialists to update.
   */
  limit?: number
}

/**
 * specialists upsert
 */
export type specialistsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
  /**
   * The filter to search for the specialists to update in case it exists.
   */
  where: Prisma.specialistsWhereUniqueInput
  /**
   * In case the specialists found by the `where` argument doesn't exist, create a new specialists with this data.
   */
  create: Prisma.XOR<Prisma.specialistsCreateInput, Prisma.specialistsUncheckedCreateInput>
  /**
   * In case the specialists was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.specialistsUpdateInput, Prisma.specialistsUncheckedUpdateInput>
}

/**
 * specialists delete
 */
export type specialistsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
  /**
   * Filter which specialists to delete.
   */
  where: Prisma.specialistsWhereUniqueInput
}

/**
 * specialists deleteMany
 */
export type specialistsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which specialists to delete
   */
  where?: Prisma.specialistsWhereInput
  /**
   * Limit how many specialists to delete.
   */
  limit?: number
}

/**
 * specialists.appointments
 */
export type specialists$appointmentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the appointments
   */
  select?: Prisma.appointmentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the appointments
   */
  omit?: Prisma.appointmentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.appointmentsInclude<ExtArgs> | null
  where?: Prisma.appointmentsWhereInput
  orderBy?: Prisma.appointmentsOrderByWithRelationInput | Prisma.appointmentsOrderByWithRelationInput[]
  cursor?: Prisma.appointmentsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentsScalarFieldEnum | Prisma.AppointmentsScalarFieldEnum[]
}

/**
 * specialists.services
 */
export type specialists$servicesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the services
   */
  select?: Prisma.servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the services
   */
  omit?: Prisma.servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.servicesInclude<ExtArgs> | null
  where?: Prisma.servicesWhereInput
  orderBy?: Prisma.servicesOrderByWithRelationInput | Prisma.servicesOrderByWithRelationInput[]
  cursor?: Prisma.servicesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ServicesScalarFieldEnum | Prisma.ServicesScalarFieldEnum[]
}

/**
 * specialists.specialist_hours
 */
export type specialists$specialist_hoursArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialist_hours
   */
  select?: Prisma.specialist_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialist_hours
   */
  omit?: Prisma.specialist_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialist_hoursInclude<ExtArgs> | null
  where?: Prisma.specialist_hoursWhereInput
  orderBy?: Prisma.specialist_hoursOrderByWithRelationInput | Prisma.specialist_hoursOrderByWithRelationInput[]
  cursor?: Prisma.specialist_hoursWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Specialist_hoursScalarFieldEnum | Prisma.Specialist_hoursScalarFieldEnum[]
}

/**
 * specialists without action
 */
export type specialistsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the specialists
   */
  select?: Prisma.specialistsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specialists
   */
  omit?: Prisma.specialistsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specialistsInclude<ExtArgs> | null
}
