/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `specializations` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.ts'
import type * as Prisma from '../internal/prismaNamespace.ts'

/**
 * Model specializations
 *
 */
export type specializationsModel = runtime.Types.Result.DefaultSelection<Prisma.$specializationsPayload>

export type AggregateSpecializations = {
  _count: SpecializationsCountAggregateOutputType | null
  _min: SpecializationsMinAggregateOutputType | null
  _max: SpecializationsMaxAggregateOutputType | null
}

export type SpecializationsMinAggregateOutputType = {
  id: string | null
  name: string | null
}

export type SpecializationsMaxAggregateOutputType = {
  id: string | null
  name: string | null
}

export type SpecializationsCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}

export type SpecializationsMinAggregateInputType = {
  id?: true
  name?: true
}

export type SpecializationsMaxAggregateInputType = {
  id?: true
  name?: true
}

export type SpecializationsCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type SpecializationsAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which specializations to aggregate.
   */
  where?: Prisma.specializationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of specializations to fetch.
   */
  orderBy?: Prisma.specializationsOrderByWithRelationInput | Prisma.specializationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.specializationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` specializations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` specializations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned specializations
   **/
  _count?: true | SpecializationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: SpecializationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: SpecializationsMaxAggregateInputType
}

export type GetSpecializationsAggregateType<T extends SpecializationsAggregateArgs> = {
  [P in keyof T & keyof AggregateSpecializations]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSpecializations[P]>
    : Prisma.GetScalarType<T[P], AggregateSpecializations[P]>
}

export type specializationsGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.specializationsWhereInput
  orderBy?: Prisma.specializationsOrderByWithAggregationInput | Prisma.specializationsOrderByWithAggregationInput[]
  by: Prisma.SpecializationsScalarFieldEnum[] | Prisma.SpecializationsScalarFieldEnum
  having?: Prisma.specializationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SpecializationsCountAggregateInputType | true
  _min?: SpecializationsMinAggregateInputType
  _max?: SpecializationsMaxAggregateInputType
}

export type SpecializationsGroupByOutputType = {
  id: string
  name: string
  _count: SpecializationsCountAggregateOutputType | null
  _min: SpecializationsMinAggregateOutputType | null
  _max: SpecializationsMaxAggregateOutputType | null
}

export type GetSpecializationsGroupByPayload<T extends specializationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SpecializationsGroupByOutputType, T['by']> & {
      [P in keyof T & keyof SpecializationsGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], SpecializationsGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], SpecializationsGroupByOutputType[P]>
    }
  >
>

export type specializationsWhereInput = {
  AND?: Prisma.specializationsWhereInput | Prisma.specializationsWhereInput[]
  OR?: Prisma.specializationsWhereInput[]
  NOT?: Prisma.specializationsWhereInput | Prisma.specializationsWhereInput[]
  id?: Prisma.UuidFilter<'specializations'> | string
  name?: Prisma.StringFilter<'specializations'> | string
  service_names?: Prisma.Service_namesListRelationFilter
}

export type specializationsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  service_names?: Prisma.service_namesOrderByRelationAggregateInput
}

export type specializationsWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    name?: string
    AND?: Prisma.specializationsWhereInput | Prisma.specializationsWhereInput[]
    OR?: Prisma.specializationsWhereInput[]
    NOT?: Prisma.specializationsWhereInput | Prisma.specializationsWhereInput[]
    service_names?: Prisma.Service_namesListRelationFilter
  },
  'id' | 'name'
>

export type specializationsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.specializationsCountOrderByAggregateInput
  _max?: Prisma.specializationsMaxOrderByAggregateInput
  _min?: Prisma.specializationsMinOrderByAggregateInput
}

export type specializationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.specializationsScalarWhereWithAggregatesInput | Prisma.specializationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.specializationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.specializationsScalarWhereWithAggregatesInput | Prisma.specializationsScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<'specializations'> | string
  name?: Prisma.StringWithAggregatesFilter<'specializations'> | string
}

export type specializationsCreateInput = {
  id?: string
  name: string
  service_names?: Prisma.service_namesCreateNestedManyWithoutSpecializationsInput
}

export type specializationsUncheckedCreateInput = {
  id?: string
  name: string
  service_names?: Prisma.service_namesUncheckedCreateNestedManyWithoutSpecializationsInput
}

export type specializationsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  service_names?: Prisma.service_namesUpdateManyWithoutSpecializationsNestedInput
}

export type specializationsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  service_names?: Prisma.service_namesUncheckedUpdateManyWithoutSpecializationsNestedInput
}

export type specializationsCreateManyInput = {
  id?: string
  name: string
}

export type specializationsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type specializationsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type SpecializationsScalarRelationFilter = {
  is?: Prisma.specializationsWhereInput
  isNot?: Prisma.specializationsWhereInput
}

export type specializationsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type specializationsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type specializationsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type specializationsCreateNestedOneWithoutService_namesInput = {
  create?: Prisma.XOR<
    Prisma.specializationsCreateWithoutService_namesInput,
    Prisma.specializationsUncheckedCreateWithoutService_namesInput
  >
  connectOrCreate?: Prisma.specializationsCreateOrConnectWithoutService_namesInput
  connect?: Prisma.specializationsWhereUniqueInput
}

export type specializationsUpdateOneRequiredWithoutService_namesNestedInput = {
  create?: Prisma.XOR<
    Prisma.specializationsCreateWithoutService_namesInput,
    Prisma.specializationsUncheckedCreateWithoutService_namesInput
  >
  connectOrCreate?: Prisma.specializationsCreateOrConnectWithoutService_namesInput
  upsert?: Prisma.specializationsUpsertWithoutService_namesInput
  connect?: Prisma.specializationsWhereUniqueInput
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.specializationsUpdateToOneWithWhereWithoutService_namesInput,
      Prisma.specializationsUpdateWithoutService_namesInput
    >,
    Prisma.specializationsUncheckedUpdateWithoutService_namesInput
  >
}

export type specializationsCreateWithoutService_namesInput = {
  id?: string
  name: string
}

export type specializationsUncheckedCreateWithoutService_namesInput = {
  id?: string
  name: string
}

export type specializationsCreateOrConnectWithoutService_namesInput = {
  where: Prisma.specializationsWhereUniqueInput
  create: Prisma.XOR<
    Prisma.specializationsCreateWithoutService_namesInput,
    Prisma.specializationsUncheckedCreateWithoutService_namesInput
  >
}

export type specializationsUpsertWithoutService_namesInput = {
  update: Prisma.XOR<
    Prisma.specializationsUpdateWithoutService_namesInput,
    Prisma.specializationsUncheckedUpdateWithoutService_namesInput
  >
  create: Prisma.XOR<
    Prisma.specializationsCreateWithoutService_namesInput,
    Prisma.specializationsUncheckedCreateWithoutService_namesInput
  >
  where?: Prisma.specializationsWhereInput
}

export type specializationsUpdateToOneWithWhereWithoutService_namesInput = {
  where?: Prisma.specializationsWhereInput
  data: Prisma.XOR<
    Prisma.specializationsUpdateWithoutService_namesInput,
    Prisma.specializationsUncheckedUpdateWithoutService_namesInput
  >
}

export type specializationsUpdateWithoutService_namesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type specializationsUncheckedUpdateWithoutService_namesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

/**
 * Count Type SpecializationsCountOutputType
 */

export type SpecializationsCountOutputType = {
  service_names: number
}

export type SpecializationsCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  service_names?: boolean | SpecializationsCountOutputTypeCountService_namesArgs
}

/**
 * SpecializationsCountOutputType without action
 */
export type SpecializationsCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the SpecializationsCountOutputType
   */
  select?: Prisma.SpecializationsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SpecializationsCountOutputType without action
 */
export type SpecializationsCountOutputTypeCountService_namesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.service_namesWhereInput
}

export type specializationsSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
    service_names?: boolean | Prisma.specializations$service_namesArgs<ExtArgs>
    _count?: boolean | Prisma.SpecializationsCountOutputTypeDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['specializations']
>

export type specializationsSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
  },
  ExtArgs['result']['specializations']
>

export type specializationsSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    name?: boolean
  },
  ExtArgs['result']['specializations']
>

export type specializationsSelectScalar = {
  id?: boolean
  name?: boolean
}

export type specializationsOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<'id' | 'name', ExtArgs['result']['specializations']>
export type specializationsInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  service_names?: boolean | Prisma.specializations$service_namesArgs<ExtArgs>
  _count?: boolean | Prisma.SpecializationsCountOutputTypeDefaultArgs<ExtArgs>
}
export type specializationsIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {}
export type specializationsIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {}

export type $specializationsPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'specializations'
  objects: {
    service_names: Prisma.$service_namesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      name: string
    },
    ExtArgs['result']['specializations']
  >
  composites: {}
}

export type specializationsGetPayload<S extends boolean | null | undefined | specializationsDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$specializationsPayload, S>

export type specializationsCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<specializationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: SpecializationsCountAggregateInputType | true
}

export interface specializationsDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['specializations']; meta: { name: 'specializations' } }
  /**
   * Find zero or one Specializations that matches the filter.
   * @param {specializationsFindUniqueArgs} args - Arguments to find a Specializations
   * @example
   * // Get one Specializations
   * const specializations = await prisma.specializations.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends specializationsFindUniqueArgs>(
    args: Prisma.SelectSubset<T, specializationsFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__specializationsClient<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'findUnique', GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one Specializations that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {specializationsFindUniqueOrThrowArgs} args - Arguments to find a Specializations
   * @example
   * // Get one Specializations
   * const specializations = await prisma.specializations.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends specializationsFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, specializationsFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__specializationsClient<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Specializations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specializationsFindFirstArgs} args - Arguments to find a Specializations
   * @example
   * // Get one Specializations
   * const specializations = await prisma.specializations.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends specializationsFindFirstArgs>(
    args?: Prisma.SelectSubset<T, specializationsFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__specializationsClient<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'findFirst', GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Specializations that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specializationsFindFirstOrThrowArgs} args - Arguments to find a Specializations
   * @example
   * // Get one Specializations
   * const specializations = await prisma.specializations.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends specializationsFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, specializationsFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__specializationsClient<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'findFirstOrThrow', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more Specializations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specializationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Specializations
   * const specializations = await prisma.specializations.findMany()
   *
   * // Get first 10 Specializations
   * const specializations = await prisma.specializations.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const specializationsWithIdOnly = await prisma.specializations.findMany({ select: { id: true } })
   *
   */
  findMany<T extends specializationsFindManyArgs>(
    args?: Prisma.SelectSubset<T, specializationsFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>
  >

  /**
   * Create a Specializations.
   * @param {specializationsCreateArgs} args - Arguments to create a Specializations.
   * @example
   * // Create one Specializations
   * const Specializations = await prisma.specializations.create({
   *   data: {
   *     // ... data to create a Specializations
   *   }
   * })
   *
   */
  create<T extends specializationsCreateArgs>(
    args: Prisma.SelectSubset<T, specializationsCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__specializationsClient<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many Specializations.
   * @param {specializationsCreateManyArgs} args - Arguments to create many Specializations.
   * @example
   * // Create many Specializations
   * const specializations = await prisma.specializations.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends specializationsCreateManyArgs>(
    args?: Prisma.SelectSubset<T, specializationsCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Specializations and returns the data saved in the database.
   * @param {specializationsCreateManyAndReturnArgs} args - Arguments to create many Specializations.
   * @example
   * // Create many Specializations
   * const specializations = await prisma.specializations.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many Specializations and only return the `id`
   * const specializationsWithIdOnly = await prisma.specializations.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends specializationsCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, specializationsCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'createManyAndReturn', GlobalOmitOptions>
  >

  /**
   * Delete a Specializations.
   * @param {specializationsDeleteArgs} args - Arguments to delete one Specializations.
   * @example
   * // Delete one Specializations
   * const Specializations = await prisma.specializations.delete({
   *   where: {
   *     // ... filter to delete one Specializations
   *   }
   * })
   *
   */
  delete<T extends specializationsDeleteArgs>(
    args: Prisma.SelectSubset<T, specializationsDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__specializationsClient<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one Specializations.
   * @param {specializationsUpdateArgs} args - Arguments to update one Specializations.
   * @example
   * // Update one Specializations
   * const specializations = await prisma.specializations.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends specializationsUpdateArgs>(
    args: Prisma.SelectSubset<T, specializationsUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__specializationsClient<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more Specializations.
   * @param {specializationsDeleteManyArgs} args - Arguments to filter Specializations to delete.
   * @example
   * // Delete a few Specializations
   * const { count } = await prisma.specializations.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends specializationsDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, specializationsDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Specializations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specializationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Specializations
   * const specializations = await prisma.specializations.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends specializationsUpdateManyArgs>(
    args: Prisma.SelectSubset<T, specializationsUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Specializations and returns the data updated in the database.
   * @param {specializationsUpdateManyAndReturnArgs} args - Arguments to update many Specializations.
   * @example
   * // Update many Specializations
   * const specializations = await prisma.specializations.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more Specializations and only return the `id`
   * const specializationsWithIdOnly = await prisma.specializations.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends specializationsUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, specializationsUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'updateManyAndReturn', GlobalOmitOptions>
  >

  /**
   * Create or update one Specializations.
   * @param {specializationsUpsertArgs} args - Arguments to update or create a Specializations.
   * @example
   * // Update or create a Specializations
   * const specializations = await prisma.specializations.upsert({
   *   create: {
   *     // ... data to create a Specializations
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Specializations we want to update
   *   }
   * })
   */
  upsert<T extends specializationsUpsertArgs>(
    args: Prisma.SelectSubset<T, specializationsUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__specializationsClient<
    runtime.Types.Result.GetResult<Prisma.$specializationsPayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of Specializations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specializationsCountArgs} args - Arguments to filter Specializations to count.
   * @example
   * // Count the number of Specializations
   * const count = await prisma.specializations.count({
   *   where: {
   *     // ... the filter for the Specializations we want to count
   *   }
   * })
   **/
  count<T extends specializationsCountArgs>(
    args?: Prisma.Subset<T, specializationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SpecializationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Specializations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpecializationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends SpecializationsAggregateArgs>(
    args: Prisma.Subset<T, SpecializationsAggregateArgs>,
  ): Prisma.PrismaPromise<GetSpecializationsAggregateType<T>>

  /**
   * Group by Specializations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {specializationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends specializationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: specializationsGroupByArgs['orderBy'] }
      : { orderBy?: specializationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, specializationsGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetSpecializationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the specializations model
   */
  readonly fields: specializationsFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for specializations.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__specializationsClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  service_names<T extends Prisma.specializations$service_namesArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.specializations$service_namesArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$service_namesPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions> | Null
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the specializations model
 */
export interface specializationsFieldRefs {
  readonly id: Prisma.FieldRef<'specializations', 'String'>
  readonly name: Prisma.FieldRef<'specializations', 'String'>
}

// Custom InputTypes
/**
 * specializations findUnique
 */
export type specializationsFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
  /**
   * Filter, which specializations to fetch.
   */
  where: Prisma.specializationsWhereUniqueInput
}

/**
 * specializations findUniqueOrThrow
 */
export type specializationsFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
  /**
   * Filter, which specializations to fetch.
   */
  where: Prisma.specializationsWhereUniqueInput
}

/**
 * specializations findFirst
 */
export type specializationsFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
  /**
   * Filter, which specializations to fetch.
   */
  where?: Prisma.specializationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of specializations to fetch.
   */
  orderBy?: Prisma.specializationsOrderByWithRelationInput | Prisma.specializationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for specializations.
   */
  cursor?: Prisma.specializationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` specializations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` specializations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of specializations.
   */
  distinct?: Prisma.SpecializationsScalarFieldEnum | Prisma.SpecializationsScalarFieldEnum[]
}

/**
 * specializations findFirstOrThrow
 */
export type specializationsFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
  /**
   * Filter, which specializations to fetch.
   */
  where?: Prisma.specializationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of specializations to fetch.
   */
  orderBy?: Prisma.specializationsOrderByWithRelationInput | Prisma.specializationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for specializations.
   */
  cursor?: Prisma.specializationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` specializations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` specializations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of specializations.
   */
  distinct?: Prisma.SpecializationsScalarFieldEnum | Prisma.SpecializationsScalarFieldEnum[]
}

/**
 * specializations findMany
 */
export type specializationsFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
  /**
   * Filter, which specializations to fetch.
   */
  where?: Prisma.specializationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of specializations to fetch.
   */
  orderBy?: Prisma.specializationsOrderByWithRelationInput | Prisma.specializationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing specializations.
   */
  cursor?: Prisma.specializationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` specializations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` specializations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of specializations.
   */
  distinct?: Prisma.SpecializationsScalarFieldEnum | Prisma.SpecializationsScalarFieldEnum[]
}

/**
 * specializations create
 */
export type specializationsCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
  /**
   * The data needed to create a specializations.
   */
  data: Prisma.XOR<Prisma.specializationsCreateInput, Prisma.specializationsUncheckedCreateInput>
}

/**
 * specializations createMany
 */
export type specializationsCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many specializations.
   */
  data: Prisma.specializationsCreateManyInput | Prisma.specializationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * specializations createManyAndReturn
 */
export type specializationsCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * The data used to create many specializations.
   */
  data: Prisma.specializationsCreateManyInput | Prisma.specializationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * specializations update
 */
export type specializationsUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
  /**
   * The data needed to update a specializations.
   */
  data: Prisma.XOR<Prisma.specializationsUpdateInput, Prisma.specializationsUncheckedUpdateInput>
  /**
   * Choose, which specializations to update.
   */
  where: Prisma.specializationsWhereUniqueInput
}

/**
 * specializations updateMany
 */
export type specializationsUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update specializations.
   */
  data: Prisma.XOR<Prisma.specializationsUpdateManyMutationInput, Prisma.specializationsUncheckedUpdateManyInput>
  /**
   * Filter which specializations to update
   */
  where?: Prisma.specializationsWhereInput
  /**
   * Limit how many specializations to update.
   */
  limit?: number
}

/**
 * specializations updateManyAndReturn
 */
export type specializationsUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * The data used to update specializations.
   */
  data: Prisma.XOR<Prisma.specializationsUpdateManyMutationInput, Prisma.specializationsUncheckedUpdateManyInput>
  /**
   * Filter which specializations to update
   */
  where?: Prisma.specializationsWhereInput
  /**
   * Limit how many specializations to update.
   */
  limit?: number
}

/**
 * specializations upsert
 */
export type specializationsUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
  /**
   * The filter to search for the specializations to update in case it exists.
   */
  where: Prisma.specializationsWhereUniqueInput
  /**
   * In case the specializations found by the `where` argument doesn't exist, create a new specializations with this data.
   */
  create: Prisma.XOR<Prisma.specializationsCreateInput, Prisma.specializationsUncheckedCreateInput>
  /**
   * In case the specializations was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.specializationsUpdateInput, Prisma.specializationsUncheckedUpdateInput>
}

/**
 * specializations delete
 */
export type specializationsDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
  /**
   * Filter which specializations to delete.
   */
  where: Prisma.specializationsWhereUniqueInput
}

/**
 * specializations deleteMany
 */
export type specializationsDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which specializations to delete
   */
  where?: Prisma.specializationsWhereInput
  /**
   * Limit how many specializations to delete.
   */
  limit?: number
}

/**
 * specializations.service_names
 */
export type specializations$service_namesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the service_names
   */
  select?: Prisma.service_namesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the service_names
   */
  omit?: Prisma.service_namesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.service_namesInclude<ExtArgs> | null
  where?: Prisma.service_namesWhereInput
  orderBy?: Prisma.service_namesOrderByWithRelationInput | Prisma.service_namesOrderByWithRelationInput[]
  cursor?: Prisma.service_namesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Service_namesScalarFieldEnum | Prisma.Service_namesScalarFieldEnum[]
}

/**
 * specializations without action
 */
export type specializationsDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the specializations
   */
  select?: Prisma.specializationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the specializations
   */
  omit?: Prisma.specializationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.specializationsInclude<ExtArgs> | null
}
