/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts'
/**
 * Model admins
 *
 */
export type admins = Prisma.adminsModel
/**
 * Model appointments
 *
 */
export type appointments = Prisma.appointmentsModel
/**
 * Model customers
 *
 */
export type customers = Prisma.customersModel
/**
 * Model secretaries
 *
 */
export type secretaries = Prisma.secretariesModel
/**
 * Model service_names
 *
 */
export type service_names = Prisma.service_namesModel
/**
 * Model services
 *
 */
export type services = Prisma.servicesModel
/**
 * Model specialist_hours
 *
 */
export type specialist_hours = Prisma.specialist_hoursModel
/**
 * Model specialists
 *
 */
export type specialists = Prisma.specialistsModel
/**
 * Model specializations
 *
 */
export type specializations = Prisma.specializationsModel
