/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/admins.ts'
export type * from './models/appointments.ts'
export type * from './models/customers.ts'
export type * from './models/secretaries.ts'
export type * from './models/service_names.ts'
export type * from './models/services.ts'
export type * from './models/specialist_hours.ts'
export type * from './models/specialists.ts'
export type * from './models/specializations.ts'
export type * from './commonInputTypes.ts'
