# @name HealthCheck

GET {{$dotenv BASE_URL}}/api/health/check

###

# @name HealthLive

# Load test (only NodeJS):
# ab -l -n 1000 -c 100 http://127.0.0.1:3000/api/health/live
# Load test (NodeJS & Bun):
# wrk -t4 -c100 -d30s --latency http://127.0.0.1:3000/api/health/live 
GET {{$dotenv BASE_URL}}/api/health/live

### 

# @name HealthReady

GET {{$dotenv BASE_URL}}/api/health/ready
