# @name GetSecretaries

GET {{$dotenv BASE_URL}}/secretaries
    ?page=0
    &pageSize=20
    # &name=Ar
    # &phone=1185386773
    # &cpf=04718413079
    # &cnpj=29616740000139
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json

### 

# @name GetSecretariesCount

GET {{$dotenv BASE_URL}}/secretaries/count
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json

### 

# @name GetSecretary

GET {{$dotenv BASE_URL}}/secretaries/ba3ac792-570c-4f42-b180-d4f4ef9388fa
Authorization: Bearer {{$dotenv TOKEN}}
Accept: application/json

### 

# @name CreateSecretary

POST {{$dotenv BASE_URL}}/secretaries
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json
{
    "name": "Secretario X",
    "email": "secretario@domain.com",
    "password": "$2a$10$p067rb/ourE4J5LRGHmSd.hyHy5LT/h1JgsyrzBHKAUlOBLLCJAPW",
    "phone": "1185386773",
    "birthdate": "1963-09-29",
    "cpf": "16520424315",
    "cnpj": "35821044000167"
}

### 

# @name UpdateSecretary

PUT {{$dotenv BASE_URL}}/secretaries/3c17daae-7209-4754-9735-0d9f7cbfdd7b
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json
{
    "name": "Kauan Ferreira Dias",
    "email": "KauanFerreiraDias@armyspy.com",
    "password": "$2a$10$p067rb/ourE4J5LRGHmSd.hyHy5LT/h1JgsyrzBHKAUlOBLLCJAPW",
    "phone": "1185386773",
    "birthdate": "1963-09-29",
    "cpf": "16520424315",
    "cnpj": "35821044000167"
}

###

# @name DeleteSecretary

DELETE {{$dotenv BASE_URL}}/secretaries/5e727cc3-3c70-4d52-9087-c68342c7033c
Authorization: Bearer {{$dotenv TOKEN}}
