import path from 'node:path'
import { WriteStr, type Writable } from '../../lib/writable'
import { BUNDLE_PATH, ROUTES_PATH } from './_config'

function generateRoutes(w: Writable) {
  const stats = { routeCount: 0 }
  const openApiJson = JSON.parse(BUNDLE_PATH.readText())

  w.write(`// Code generated by ${path.basename(import.meta.filename)} - DO NOT EDIT.\n\n`)
  w.write("import { bindResolver as h } from './adapter-wrap'\n")
  w.write("import resolvers from './resolvers'\n")
  w.write('\n')
  w.write('export const routes = {\n')
  for (const url in openApiJson.paths) {
    const bunUrl = url.replaceAll(/\{(\w+)\}/g, ':$1')
    w.write(`  '${bunUrl}': {\n`)
    const path = (openApiJson.paths as any)[url]
    for (const method in path) {
      const endpoint = path[method]
      w.write(`    ${method.toUpperCase()}: h(resolvers.${endpoint.operationId}),\n`)
      stats.routeCount++
    }
    w.write('  },\n')
  }
  w.write("} satisfies Bun.Serve.Options<any, any>['routes']\n")

  return stats
}

const w = new WriteStr()
const stats = generateRoutes(w)
ROUTES_PATH.writeText(w.value())
console.log(`ok: routes      file: ${ROUTES_PATH} count: ${stats.routeCount}`)
