export namespace domain {
  /**
   * @description: Example: 019dcd01-5a4a-736f-9407-8e69aa9433bc
   * @format: uuid
   * @maxLength: 36
   */
  export type Uuid = string

  /**
   * @description: in cents
   * @format: integer
   * @minimum: 0
   */
  export type Price = number

  /**
   * @description: in minutes
   * @format: integer
   * @minimum: 0
   * @maximum: 600
   */
  export type Duration = number

  /**
   * @format: email
   * @minLength: 1
   * @maxLength: 200
   */
  export type Email = string

  /**
   * @maxLength: 36
   */
  export type Role = string

  /**
   * @minLength: 1
   * @maxLength: 30
   */
  export type Password = string

  /**
   * @format: phone
   * @maxLength: 20
   */
  export type Phone = string

  /**
   * @format: cpf
   * @minLength: 11
   * @maxLength: 11
   */
  export type Cpf = string

  /**
   * @format: cnpj
   * @minLength: 14
   * @maxLength: 14
   */
  export type Cnpj = string

  /**
   * @description: Non empty string
   * @minLength: 1
   * @maxLength: 200
   */
  export type Name = string

  /**
   * @description: date only string in format YYYY-MM-DD
   * @format: date
   * @minLength: 10
   * @maxLength: 10
   */
  export type Date = string

  /**
   * @description: time only string in format HH-MM-SS
   * @format: time
   * @minLength: 8
   * @maxLength: 8
   */
  export type Time = string

  export type Resource = //
    | 'appointment' //
    | 'customer'
    | 'secretary'
    | 'service'
    | 'service_name'
    | 'specialist'
    | 'specialization'
}

export namespace schemas {
  /**
   * @description: Standard error response based on RFC 7807.
   */
  export interface ProblemDetails {
    /**
     * @description: A machine-readable, domain-specific error code used by clients to implement conditional logic.
     */
    code: //
      | 'auth_error' //
      | 'forbidden_error'
      | 'validation_error'
      | 'resource_not_found'
      | 'resource_conflict'
      | 'internal_error'
    /**
     * @description: A URI reference that identifies the error type. Ideally points to documentation describing the error.
     * @format: uri
     */
    type: string
    /**
     * @description: A short, human-readable summary of the problem type.
     */
    title: string
    /**
     * @description: The HTTP status code generated by the origin server for this occurrence of the problem.
     */
    status: number
    /**
     * @description: A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string
    /**
     * @description: A URI reference that identifies the specific occurrence of the problem (e.g., the request path or a correlation URI).
     */
    instance?: string
    /**
     * @description: A unique identifier for tracing the request across systems.
     */
    traceId?: string
    source?: {
      in: 'body' | 'path' | 'query'
      path: string
    }
    /**
     * @description: A dictionary of validation errors where each key is a field or parameter name and the value is an array of error messages associated with that field.
     */
    errors?: Record<string, string[]>
  }

  export interface Id {
    id: domain.Uuid
  }

  export type Count = number

  export interface Status {
    status: boolean
    /**
     * @format: datetime
     */
    updatedAt: string
    environment: string
    database?: {
      status: 'connected' | 'disconnected'
      version: string
      maxConnections: number
      openedConnections: number
      schemaVersion: number
    }
  }

  export interface AuthResponse {
    accessToken: string
    refreshToken: string
  }

  export interface AuthIdentity {
    id: domain.Uuid
    name: domain.Name
    email: domain.Email
    role: domain.Role
  }

  /**
   * @description: 0: None 1: Pending 2: Realized 3: Canceled
   */
  export type AppointmentStatus = number

  export interface Appointment {
    id: domain.Uuid
    customerName: domain.Name
    customerId: domain.Uuid
    serviceName: domain.Name
    serviceNameId: domain.Uuid
    specialistName: domain.Name
    specialistId: domain.Uuid
    price: domain.Price
    duration: domain.Duration
    date: domain.Date
    time: domain.Time
    status: schemas.AppointmentStatus
  }

  export type AppointmentCalendarCount = {
    month: number
    pendingCount: number
    realizedCount: number
    canceledCount: number
  }

  export interface AppointmentCalendar {
    id: domain.Uuid
    date: domain.Date
    time: domain.Time
    specialistName: domain.Name
    status: schemas.AppointmentStatus
  }

  export interface Customer {
    id: domain.Uuid
    name: domain.Name
    email?: domain.Email
    phone: domain.Phone
    birthdate: domain.Date
    cpf: domain.Cpf
  }

  export interface Secretary {
    id: domain.Uuid
    name: domain.Name
    email: domain.Email
    phone: domain.Phone
    birthdate: domain.Date
    cpf: domain.Cpf
    cnpj?: domain.Cnpj
  }

  export interface ServiceAvailable {
    serviceNameId?: domain.Uuid
    serviceName?: domain.Name
    specializationId?: domain.Uuid
    specialization?: domain.Name
  }

  export interface ServiceEnriched {
    id: domain.Uuid
    serviceName: domain.Name
    serviceNameId: domain.Uuid
    specialistName: domain.Name
    specialistId: domain.Uuid
    specialization: domain.Name
    specializationId: domain.Uuid
    price: domain.Price
    duration: domain.Duration
  }

  export interface Service {
    id: domain.Uuid
    serviceNameId: domain.Uuid
    specialistId: domain.Uuid
    price: domain.Price
    duration: domain.Duration
  }

  export interface ServiceGroup {
    id: domain.Uuid
    name: domain.Name
    items: Array<{
      id: domain.Uuid
      name: domain.Name
    }>
  }

  export interface Specialist {
    id: domain.Uuid
    name: domain.Name
    email: domain.Email
    phone: domain.Phone
    birthdate: domain.Date
    cpf: domain.Cpf
    cnpj?: domain.Cnpj
  }

  export interface SpecialistAppointment {
    id: domain.Uuid
    customerName: domain.Name
    customerId: domain.Uuid
    serviceName: domain.Name
    serviceNameId: domain.Uuid
    price: domain.Price
    duration: domain.Duration
    date: domain.Date
    time: domain.Time
    status: schemas.AppointmentStatus
  }

  export interface SpecialistService {
    id: domain.Uuid
    specializationId: domain.Uuid
    serviceName: domain.Name
    serviceNameId: domain.Uuid
    price: domain.Price
    duration: domain.Duration
  }

  export interface Specialization {
    id: domain.Uuid
    name: domain.Name
  }
}

export namespace body {
  export interface AuthLogin {
    email: domain.Email
    password: domain.Password
  }

  export interface AppointmentsCreateBody {
    customerId: domain.Uuid
    serviceId: domain.Uuid
    date: domain.Date
    time: domain.Time
  }

  export interface AppointmentsUpdateBody {
    date: domain.Date
    time: domain.Time
    status: schemas.AppointmentStatus
  }

  export interface CustomerCreateBody {
    name: domain.Name
    email: domain.Email
    phone: domain.Phone
    birthdate: domain.Date
    cpf: domain.Cpf
  }

  export interface CustomerUpdateBody {
    name: domain.Name
    email: domain.Email
    phone: domain.Phone
    birthdate: domain.Date
    cpf: domain.Cpf
  }

  export interface SecretaryCreateBody {
    name: domain.Name
    email: domain.Email
    phone: domain.Phone
    birthdate: domain.Date
    password: domain.Password
    cpf: domain.Cpf
    cnpj: domain.Cnpj
  }

  export interface SecretaryUpdateBody {
    name: domain.Name
    email: domain.Email
    phone: domain.Phone
    birthdate: domain.Date
    password?: domain.Password
    cpf: domain.Cpf
    cnpj: domain.Cnpj
  }

  export interface ServiceAvailableCreateBody {
    name: domain.Name
    specialization?: domain.Name
    specializationId?: domain.Uuid
  }

  export interface ServiceAvailableUpdateBody {
    name: domain.Name
  }

  export interface ServiceCreateBody {
    specialistId: domain.Uuid
    serviceNameId: domain.Uuid
    price: domain.Price
    duration: domain.Duration
  }

  export interface ServiceUpdateBody {
    price: domain.Price
    duration: domain.Duration
  }

  export interface SpecialistsCreateBodyService {
    serviceNameId: domain.Uuid
    price: domain.Price
    duration: domain.Duration
  }

  export interface SpecialistCreateBody {
    name: domain.Name
    email: domain.Email
    phone: domain.Phone
    birthdate: domain.Date
    cpf: domain.Cpf
    cnpj: domain.Cnpj
    services: body.SpecialistsCreateBodyService[]
  }

  export interface SpecialistUpdateBody {
    name: domain.Name
    email: domain.Email
    phone: domain.Phone
    birthdate: domain.Date
    cpf: domain.Cpf
    cnpj: domain.Cnpj
    services: body.SpecialistsCreateBodyService[]
  }

  export interface SpecializationCreateBody {
    name: domain.Name
  }

  export interface SpecializationUpdateBody {
    name: domain.Name
  }
}

export namespace query {
  export type StartDate = domain.Date

  export type EndDate = domain.Date

  export type ServiceName = domain.Name

  export type Service = domain.Name

  export type Specialist = domain.Name

  export type Specialization = domain.Name

  export type Customer = domain.Name

  export type Status = schemas.AppointmentStatus

  export type Name = domain.Name

  export type Cpf = domain.Cpf

  export type Cnpj = domain.Cnpj

  export type Phone = domain.Phone

  /**
   * @default: 0
   * @format: integer
   * @minimum: 0
   */
  export type Page = number

  /**
   * @default: 10
   * @format: integer
   * @minimum: 1
   */
  export type PageSize = number
}

export namespace api {
  export namespace health {
    export namespace healthCheck {
      export type responses = {
        /**
         * API is healthy
         */
        200: schemas.Status
      }
    }
  }

  export namespace auth {
    export namespace login {
      export type body = body.AuthLogin

      export type responses = {
        200: schemas.AuthResponse
        400: schemas.ProblemDetails
        401: schemas.ProblemDetails
      }
    }

    export namespace refresh {
      export type responses = {
        200: schemas.AuthResponse
        400: schemas.ProblemDetails
        401: schemas.ProblemDetails
        500: schemas.ProblemDetails
      }
    }

    export namespace me {
      export type responses = {
        200: schemas.AuthIdentity
        400: schemas.ProblemDetails
        401: schemas.ProblemDetails
      }
    }
  }

  export namespace appointments {
    export namespace listAppointments {
      export type query = {
        page?: query.Page
        pageSize?: query.PageSize
        startDate?: query.StartDate
        endDate?: query.EndDate
        serviceName?: query.ServiceName
        specialist?: query.Specialist
        customer?: query.Customer
        status?: query.Status
      }

      export type responses = {
        200: schemas.Appointment[]
        400: schemas.ProblemDetails
      }
    }

    export namespace createAppointment {
      export type body = body.AppointmentsCreateBody

      export type responses = {
        201: schemas.Id
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace countAppointments {
      export type query = {
        startDate?: query.StartDate
        endDate?: query.EndDate
        serviceName?: query.ServiceName
        specialist?: query.Specialist
        customer?: query.Customer
        status?: query.Status
      }

      export type responses = {
        200: schemas.Count
        400: schemas.ProblemDetails
      }
    }

    export namespace getAppointmentsCalendar {
      export type query = {
        startDate?: query.StartDate
        endDate?: query.EndDate
      }

      export type responses = {
        200: schemas.AppointmentCalendar[]
        400: schemas.ProblemDetails
      }
    }

    export namespace getAppointmentsCalendarCount {
      export type query = {
        startDate?: query.StartDate
        endDate?: query.EndDate
      }

      export type responses = {
        200: schemas.AppointmentCalendarCount[]
        400: schemas.ProblemDetails
      }
    }

    export namespace getAppointmentById {
      export type responses = {
        200: schemas.Appointment
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace updateAppointment {
      export type body = body.AppointmentsUpdateBody

      export type responses = {
        200: schemas.Id
        400: schemas.ProblemDetails
      }
    }

    export namespace deleteAppointment {
      export type responses = {
        /**
         * Item deleted successfully
         */
        204: any
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }
  }

  export namespace customers {
    export namespace listCustomers {
      export type query = {
        page?: query.Page
        pageSize?: query.PageSize
        name?: query.Name
        cpf?: query.Cpf
        phone?: query.Phone
      }

      export type responses = {
        200: schemas.Customer[]
        400: schemas.ProblemDetails
      }
    }

    export namespace createCustomer {
      export type body = body.CustomerCreateBody

      export type responses = {
        201: schemas.Id
        400: schemas.ProblemDetails
      }
    }

    export namespace countCustomers {
      export type query = {
        name?: query.Name
        cpf?: query.Cpf
        phone?: query.Phone
      }

      export type responses = {
        200: schemas.Count
        400: schemas.ProblemDetails
      }
    }

    export namespace getCustomerById {
      export type responses = {
        200: schemas.Customer
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace updateCustomer {
      export type body = body.CustomerUpdateBody

      export type responses = {
        200: schemas.Id
        400: schemas.ProblemDetails
      }
    }

    export namespace deleteCustomer {
      export type responses = {
        /**
         * Item deleted successfully
         */
        204: any
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }
  }

  export namespace secretaries {
    export namespace listSecretaries {
      export type query = {
        page?: query.Page
        pageSize?: query.PageSize
        name?: query.Name
        cpf?: query.Cpf
        cnpj?: query.Cnpj
        phone?: query.Phone
      }

      export type responses = {
        200: schemas.Secretary[]
        400: schemas.ProblemDetails
      }
    }

    export namespace createSecretary {
      export type body = body.SecretaryCreateBody

      export type responses = {
        201: schemas.Id
        400: schemas.ProblemDetails
        409: schemas.ProblemDetails
      }
    }

    export namespace countSecretaries {
      export type query = {
        name?: query.Name
        cpf?: query.Cpf
        cnpj?: query.Cnpj
        phone?: query.Phone
      }

      export type responses = {
        200: schemas.Count
        400: schemas.ProblemDetails
      }
    }

    export namespace getSecretaryById {
      export type responses = {
        200: schemas.Customer
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace updateSecretary {
      export type body = body.SecretaryUpdateBody

      export type responses = {
        200: schemas.Id
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
        409: schemas.ProblemDetails
      }
    }

    export namespace deleteSecretary {
      export type responses = {
        /**
         * Item deleted successfully
         */
        204: any
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }
  }

  export namespace servicesAvailable {
    export namespace listServicesAvailable {
      export type query = {
        page?: query.Page
        pageSize?: query.PageSize
      }

      export type responses = {
        200: schemas.ServiceGroup[]
        400: schemas.ProblemDetails
      }
    }

    export namespace createServiceAvailable {
      export type body = body.ServiceAvailableCreateBody

      export type responses = {
        201: schemas.Id
        400: schemas.ProblemDetails
        409: schemas.ProblemDetails
      }
    }

    export namespace getServiceAvailableById {
      export type responses = {
        200: schemas.ServiceAvailable
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace updateServiceAvailable {
      export type body = body.ServiceAvailableUpdateBody

      export type responses = {
        200: schemas.Id
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace deleteServiceAvailable {
      export type responses = {
        /**
         * Item deleted successfully
         */
        204: any
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }
  }

  export namespace services {
    export namespace listServices {
      export type query = {
        page?: query.Page
        pageSize?: query.PageSize
        service?: query.Service
        specialist?: query.Specialist
        specialization?: query.Specialization
      }

      export type responses = {
        200: schemas.ServiceEnriched[]
        400: schemas.ProblemDetails
      }
    }

    export namespace createService {
      export type body = body.ServiceCreateBody

      export type responses = {
        201: schemas.Id
        400: schemas.ProblemDetails
      }
    }

    export namespace countServices {
      export type query = {
        service?: query.Service
        specialist?: query.Specialist
        specialization?: query.Specialization
      }

      export type responses = {
        200: schemas.Count
        400: schemas.ProblemDetails
      }
    }

    export namespace getServiceById {
      export type responses = {
        200: schemas.Service
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace updateService {
      export type body = body.ServiceUpdateBody

      export type responses = {
        200: schemas.Id
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace deleteService {
      export type responses = {
        /**
         * Item deleted successfully
         */
        204: any
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }
  }

  export namespace serviceGroups {
    export namespace listServiceGroups {
      export type responses = {
        200: schemas.ServiceGroup[]
        400: schemas.ProblemDetails
      }
    }
  }

  export namespace specialists {
    export namespace listSpecialists {
      export type query = {
        page?: query.Page
        pageSize?: query.PageSize
        name?: query.Name
        cpf?: query.Cpf
        cnpj?: query.Cnpj
        phone?: query.Phone
      }

      export type responses = {
        200: schemas.Specialist[]
        400: schemas.ProblemDetails
      }
    }

    export namespace createSpecialist {
      export type body = body.SpecialistCreateBody

      export type responses = {
        201: schemas.Id
        400: schemas.ProblemDetails
        409: schemas.ProblemDetails
      }
    }

    export namespace countSpecialists {
      export type query = {
        name?: query.Name
        cpf?: query.Cpf
        cnpj?: query.Cnpj
        phone?: query.Phone
      }

      export type responses = {
        200: schemas.Count
        400: schemas.ProblemDetails
      }
    }

    export namespace getSpecialistServices {
      export type responses = {
        200: schemas.SpecialistService[]
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace getSpecialistSpecializations {
      export type responses = {
        200: schemas.Specialization[]
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace getSpecialistAppointments {
      export type query = {
        page?: query.Page
        pageSize?: query.PageSize
      }

      export type responses = {
        200: schemas.SpecialistAppointment[]
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace getSpecialistService {
      export type responses = {
        200: schemas.Service
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace getSpecialistById {
      export type responses = {
        200: schemas.Specialist
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace updateSpecialist {
      export type body = body.SpecialistUpdateBody

      export type responses = {
        200: schemas.Id
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace deleteSpecialist {
      export type responses = {
        /**
         * Item deleted successfully
         */
        204: any
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }
  }

  export namespace specializations {
    export namespace listSpecializations {
      export type responses = {
        200: schemas.Specialization[]
        400: schemas.ProblemDetails
      }
    }

    export namespace createSpecialization {
      export type body = body.SpecializationCreateBody

      export type responses = {
        201: schemas.Id
        400: schemas.ProblemDetails
        409: schemas.ProblemDetails
      }
    }

    export namespace updateSpecialization {
      export type body = body.SpecializationUpdateBody

      export type responses = {
        200: schemas.Id
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }

    export namespace deleteSpecialization {
      export type responses = {
        /**
         * Item deleted successfully
         */
        204: any
        400: schemas.ProblemDetails
        404: schemas.ProblemDetails
      }
    }
  }

  export namespace test {
    export namespace initTest {
      export type responses = {
        200: any
      }
    }

    export namespace statsTest {
      export type responses = {
        200: any
      }
    }

    export namespace debugClaimsTest {
      export type responses = {
        200: any
      }
    }
  }
}
