// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: health_query.sql

package infra

import (
	"context"
)

const getStatus = `-- name: GetStatus :one
SELECT 1
`

func (q *Queries) GetStatus(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getStatus)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
