// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package infra

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	ID       pgtype.UUID
	Name     string
	Email    string
	Password string
}

type Appointment struct {
	ID            pgtype.UUID
	CustomerID    pgtype.UUID
	SpecialistID  pgtype.UUID
	ServiceNameID pgtype.UUID
	Price         int32
	Duration      int32
	Date          pgtype.Date
	Time          pgtype.Time
	Status        int32
	NotifiedAt    pgtype.Timestamptz
	NotifiedBy    pgtype.UUID
}

type BillingPeriod struct {
	ID        pgtype.UUID
	StartsAt  pgtype.Timestamp
	EndsAt    pgtype.Timestamp
	Status    int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	ClosedAt  pgtype.Timestamp
}

type Customer struct {
	ID        pgtype.UUID
	Name      string
	Email     pgtype.Text
	Phone     string
	Birthdate pgtype.Date
	Cpf       string
}

type Invoice struct {
	ID              pgtype.UUID
	Number          int32
	SpecialistID    pgtype.UUID
	BillingPeriodID pgtype.UUID
	Status          int32
	GeneratedAt     pgtype.Timestamp
	ReviewedAt      pgtype.Timestamp
	ApprovedAt      pgtype.Timestamp
	FinalizedAt     pgtype.Timestamp
	SentAt          pgtype.Timestamp
}

type InvoiceItem struct {
	ID             pgtype.UUID
	InvoiceID      pgtype.UUID
	Type           int32
	SourceType     string
	Description    string
	Quantity       int32
	UnitAmount     int32
	GrossAmount    int32
	DiscountAmount int32
	TaxAmount      int32
	NetAmount      int32
}

type Secretary struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Password  string
	Phone     string
	Birthdate pgtype.Date
	Cpf       string
	Cnpj      pgtype.Text
}

type Service struct {
	ID            pgtype.UUID
	ServiceNameID pgtype.UUID
	SpecialistID  pgtype.UUID
	Price         int32
	Duration      int32
}

type ServiceName struct {
	ID               pgtype.UUID
	Name             string
	SpecializationID pgtype.UUID
}

type Specialist struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Phone     string
	Birthdate pgtype.Date
	Cpf       string
	Cnpj      pgtype.Text
}

type SpecialistHour struct {
	ID           pgtype.UUID
	SpecialistID pgtype.UUID
	Weekday      int32
	StartTime    pgtype.Time
	EndTime      pgtype.Time
}

type Specialization struct {
	ID   pgtype.UUID
	Name string
}
