// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: services_available_queries.sql

package infra

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getServiceAvailableByID = `-- name: GetServiceAvailableByID :one
SELECT "sn"."id" as "service_name_id", "sn"."name" as "service_name"
     , "sp"."id" as "specialization_id", "sp"."name" as "specialization"
FROM "service_names" "sn"
JOIN "specializations" "sp" ON "sn"."specialization_id" = "sp"."id"
WHERE "sn"."id" = $1
`

type GetServiceAvailableByIDRow struct {
	ServiceNameID    pgtype.UUID
	ServiceName      string
	SpecializationID pgtype.UUID
	Specialization   string
}

func (q *Queries) GetServiceAvailableByID(ctx context.Context, servicenameid pgtype.UUID) (GetServiceAvailableByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceAvailableByID, servicenameid)
	var i GetServiceAvailableByIDRow
	err := row.Scan(
		&i.ServiceNameID,
		&i.ServiceName,
		&i.SpecializationID,
		&i.Specialization,
	)
	return i, err
}
