// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: specializations_queries.sql

package infra

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpecialization = `-- name: CreateSpecialization :one
INSERT INTO "specializations" ("id", "name")
VALUES ( $1
			 , $2
			 )
RETURNING "id"
`

type CreateSpecializationParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) CreateSpecialization(ctx context.Context, arg CreateSpecializationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSpecialization, arg.ID, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteSpecializationByID = `-- name: DeleteSpecializationByID :execrows
DELETE FROM "specializations"
WHERE "id" = $1
`

func (q *Queries) DeleteSpecializationByID(ctx context.Context, specializationid pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpecializationByID, specializationid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSpecializationByID = `-- name: GetSpecializationByID :one
SELECT "id", "name"
FROM "specializations" 
WHERE "id" = $1
`

func (q *Queries) GetSpecializationByID(ctx context.Context, specializationid pgtype.UUID) (Specialization, error) {
	row := q.db.QueryRow(ctx, getSpecializationByID, specializationid)
	var i Specialization
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getSpecializationByName = `-- name: GetSpecializationByName :one
SELECT "id", "name"
FROM "specializations" 
WHERE "name" = $1
`

func (q *Queries) GetSpecializationByName(ctx context.Context, specializationname string) (Specialization, error) {
	row := q.db.QueryRow(ctx, getSpecializationByName, specializationname)
	var i Specialization
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listSpecializations = `-- name: ListSpecializations :many
SELECT "id", "name"
FROM "specializations"
ORDER BY "name" ASC
`

func (q *Queries) ListSpecializations(ctx context.Context) ([]Specialization, error) {
	rows, err := q.db.Query(ctx, listSpecializations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialization
	for rows.Next() {
		var i Specialization
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecializationsBySpecialistID = `-- name: ListSpecializationsBySpecialistID :many
SELECT "sp"."id", "sp"."name"
FROM "specializations" "sp"
WHERE "sp"."id" IN (
	SELECT "sn"."specialization_id" 
	FROM "services" "s" 
	JOIN "service_names" "sn" ON "sn"."id" = "s"."service_name_id"
	WHERE "s"."specialist_id" = $1
)
ORDER BY "name" ASC
`

func (q *Queries) ListSpecializationsBySpecialistID(ctx context.Context, specialistid pgtype.UUID) ([]Specialization, error) {
	rows, err := q.db.Query(ctx, listSpecializationsBySpecialistID, specialistid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialization
	for rows.Next() {
		var i Specialization
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpecialization = `-- name: UpdateSpecialization :one
UPDATE "specializations"
SET 
	"name" = $1
WHERE "id" = $2
RETURNING "id"
`

type UpdateSpecializationParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateSpecialization(ctx context.Context, arg UpdateSpecializationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, updateSpecialization, arg.Name, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
