import path from 'node:path'
import { WriteStr, type Writable } from '../../lib/writable'
import openApiJson from '../../public/api/openapi.json' with { type: 'json' }
import { ROUTES_PATH } from './_config'

function generateRoutes(w: Writable) {
  const stats = { routeCount: 0 }
  w.write(`// Code generated by ${path.basename(import.meta.filename)} - DO NOT EDIT.\n\n`)
  w.write("import { Router } from 'express'\n")
  w.write("import { expressResolversAdapter } from './adapter'\n")
  w.write('\n')
  w.write('export const routes = Router()\n\n')

  for (const url in openApiJson.paths) {
    const expressUrl = url.replaceAll(/\{(\w+)\}/g, ':$1')
    const path = (openApiJson.paths as any)[url]
    for (const method in path) {
      const endpoint = path[method]
      w.write(`routes.${method.toLowerCase()}('${expressUrl}', expressResolversAdapter('${endpoint.operationId}'))\n`)
      stats.routeCount++
    }
  }

  return stats
}

const w = new WriteStr()
const stats = generateRoutes(w)
ROUTES_PATH.writeText(w.value())
console.log(`ok: routes      file: ${ROUTES_PATH} count: ${stats.routeCount}`)
